<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateDiscountRequest;

/**
 * Builder for model CreateDiscountRequest
 *
 * @see CreateDiscountRequest
 */
class CreateDiscountRequestBuilder
{
    /**
     * @var CreateDiscountRequest
     */
    private $instance;

    private function __construct(CreateDiscountRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Discount Request Builder object.
     *
     * @param float $value
     * @param string $discountType
     * @param string $itemId
     */
    public static function init(float $value, string $discountType, string $itemId): self
    {
        return new self(new CreateDiscountRequest($value, $discountType, $itemId));
    }

    /**
     * Sets cycles field.
     *
     * @param int|null $value
     */
    public function cycles(?int $value): self
    {
        $this->instance->setCycles($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new Create Discount Request object.
     */
    public function build(): CreateDiscountRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
