<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePhoneRequest;
use PagarmeApiSDKLib\Models\CreatePhonesRequest;

/**
 * Builder for model CreatePhonesRequest
 *
 * @see CreatePhonesRequest
 */
class CreatePhonesRequestBuilder
{
    /**
     * @var CreatePhonesRequest
     */
    private $instance;

    private function __construct(CreatePhonesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Phones Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreatePhonesRequest());
    }

    /**
     * Sets home phone field.
     *
     * @param CreatePhoneRequest|null $value
     */
    public function homePhone(?CreatePhoneRequest $value): self
    {
        $this->instance->setHomePhone($value);
        return $this;
    }

    /**
     * Sets mobile phone field.
     *
     * @param CreatePhoneRequest|null $value
     */
    public function mobilePhone(?CreatePhoneRequest $value): self
    {
        $this->instance->setMobilePhone($value);
        return $this;
    }

    /**
     * Initializes a new Create Phones Request object.
     */
    public function build(): CreatePhonesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
