<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateBankAccountRefundingDTO;
use PagarmeApiSDKLib\Models\CreateCancelChargeRequest;
use PagarmeApiSDKLib\Models\CreateCancelChargeSplitRulesRequest;
use PagarmeApiSDKLib\Models\CreateSplitRequest;

/**
 * Builder for model CreateCancelChargeRequest
 *
 * @see CreateCancelChargeRequest
 */
class CreateCancelChargeRequestBuilder
{
    /**
     * @var CreateCancelChargeRequest
     */
    private $instance;

    private function __construct(CreateCancelChargeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Cancel Charge Request Builder object.
     *
     * @param string $operationReference
     */
    public static function init(string $operationReference): self
    {
        return new self(new CreateCancelChargeRequest($operationReference));
    }

    /**
     * Sets amount field.
     *
     * @param int|null $value
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets split rules field.
     *
     * @param CreateCancelChargeSplitRulesRequest[]|null $value
     */
    public function splitRules(?array $value): self
    {
        $this->instance->setSplitRules($value);
        return $this;
    }

    /**
     * Sets split field.
     *
     * @param CreateSplitRequest[]|null $value
     */
    public function split(?array $value): self
    {
        $this->instance->setSplit($value);
        return $this;
    }

    /**
     * Sets bank account field.
     *
     * @param CreateBankAccountRefundingDTO|null $value
     */
    public function bankAccount(?CreateBankAccountRefundingDTO $value): self
    {
        $this->instance->setBankAccount($value);
        return $this;
    }

    /**
     * Initializes a new Create Cancel Charge Request object.
     */
    public function build(): CreateCancelChargeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
