<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCancelSubscriptionRequest;

/**
 * Builder for model CreateCancelSubscriptionRequest
 *
 * @see CreateCancelSubscriptionRequest
 */
class CreateCancelSubscriptionRequestBuilder
{
    /**
     * @var CreateCancelSubscriptionRequest
     */
    private $instance;

    private function __construct(CreateCancelSubscriptionRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Cancel Subscription Request Builder object.
     *
     * @param bool $cancelPendingInvoices
     */
    public static function init(bool $cancelPendingInvoices): self
    {
        return new self(new CreateCancelSubscriptionRequest($cancelPendingInvoices));
    }

    /**
     * Initializes a new Create Cancel Subscription Request object.
     */
    public function build(): CreateCancelSubscriptionRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
