<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCardRequest;
use PagarmeApiSDKLib\Models\CreatePrivateLabelPaymentRequest;

/**
 * Builder for model CreatePrivateLabelPaymentRequest
 *
 * @see CreatePrivateLabelPaymentRequest
 */
class CreatePrivateLabelPaymentRequestBuilder
{
    /**
     * @var CreatePrivateLabelPaymentRequest
     */
    private $instance;

    private function __construct(CreatePrivateLabelPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Private Label Payment Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreatePrivateLabelPaymentRequest());
    }

    /**
     * Sets installments field.
     *
     * @param int|null $value
     */
    public function installments(?int $value): self
    {
        $this->instance->setInstallments($value);
        return $this;
    }

    /**
     * Sets statement descriptor field.
     *
     * @param string|null $value
     */
    public function statementDescriptor(?string $value): self
    {
        $this->instance->setStatementDescriptor($value);
        return $this;
    }

    /**
     * Sets card field.
     *
     * @param CreateCardRequest|null $value
     */
    public function card(?CreateCardRequest $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Sets card id field.
     *
     * @param string|null $value
     */
    public function cardId(?string $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets card token field.
     *
     * @param string|null $value
     */
    public function cardToken(?string $value): self
    {
        $this->instance->setCardToken($value);
        return $this;
    }

    /**
     * Sets recurrence field.
     *
     * @param bool|null $value
     */
    public function recurrence(?bool $value): self
    {
        $this->instance->setRecurrence($value);
        return $this;
    }

    /**
     * Sets capture field.
     *
     * @param bool|null $value
     */
    public function capture(?bool $value): self
    {
        $this->instance->setCapture($value);
        return $this;
    }

    /**
     * Sets extended limit enabled field.
     *
     * @param bool|null $value
     */
    public function extendedLimitEnabled(?bool $value): self
    {
        $this->instance->setExtendedLimitEnabled($value);
        return $this;
    }

    /**
     * Sets extended limit code field.
     *
     * @param string|null $value
     */
    public function extendedLimitCode(?string $value): self
    {
        $this->instance->setExtendedLimitCode($value);
        return $this;
    }

    /**
     * Sets recurrency cycle field.
     *
     * @param string|null $value
     */
    public function recurrencyCycle(?string $value): self
    {
        $this->instance->setRecurrencyCycle($value);
        return $this;
    }

    /**
     * Initializes a new Create Private Label Payment Request object.
     */
    public function build(): CreatePrivateLabelPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
