<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePriceBracketRequest;
use PagarmeApiSDKLib\Models\CreatePricingSchemeRequest;

/**
 * Builder for model CreatePricingSchemeRequest
 *
 * @see CreatePricingSchemeRequest
 */
class CreatePricingSchemeRequestBuilder
{
    /**
     * @var CreatePricingSchemeRequest
     */
    private $instance;

    private function __construct(CreatePricingSchemeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Pricing Scheme Request Builder object.
     *
     * @param string $schemeType
     */
    public static function init(string $schemeType): self
    {
        return new self(new CreatePricingSchemeRequest($schemeType));
    }

    /**
     * Sets price brackets field.
     *
     * @param CreatePriceBracketRequest[]|null $value
     */
    public function priceBrackets(?array $value): self
    {
        $this->instance->setPriceBrackets($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param int|null $value
     */
    public function price(?int $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets minimum price field.
     *
     * @param int|null $value
     */
    public function minimumPrice(?int $value): self
    {
        $this->instance->setMinimumPrice($value);
        return $this;
    }

    /**
     * Sets percentage field.
     *
     * @param float|null $value
     */
    public function percentage(?float $value): self
    {
        $this->instance->setPercentage($value);
        return $this;
    }

    /**
     * Initializes a new Create Pricing Scheme Request object.
     */
    public function build(): CreatePricingSchemeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
