<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateDeviceRequest;

/**
 * Builder for model CreateDeviceRequest
 *
 * @see CreateDeviceRequest
 */
class CreateDeviceRequestBuilder
{
    /**
     * @var CreateDeviceRequest
     */
    private $instance;

    private function __construct(CreateDeviceRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Device Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateDeviceRequest());
    }

    /**
     * Sets platform field.
     *
     * @param string|null $value
     */
    public function platform(?string $value): self
    {
        $this->instance->setPlatform($value);
        return $this;
    }

    /**
     * Initializes a new Create Device Request object.
     */
    public function build(): CreateDeviceRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
