<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAutomaticAnticipationSettingsRequest;

/**
 * Builder for model CreateAutomaticAnticipationSettingsRequest
 *
 * @see CreateAutomaticAnticipationSettingsRequest
 */
class CreateAutomaticAnticipationSettingsRequestBuilder
{
    /**
     * @var CreateAutomaticAnticipationSettingsRequest
     */
    private $instance;

    private function __construct(CreateAutomaticAnticipationSettingsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Automatic Anticipation Settings Request Builder object.
     *
     * @param bool $enabled
     * @param string $type
     * @param int $volumePercentage
     * @param int $delay
     * @param int[] $days
     */
    public static function init(bool $enabled, string $type, int $volumePercentage, int $delay, array $days): self
    {
        return new self(
            new CreateAutomaticAnticipationSettingsRequest($enabled, $type, $volumePercentage, $delay, $days)
        );
    }

    /**
     * Initializes a new Create Automatic Anticipation Settings Request object.
     */
    public function build(): CreateAutomaticAnticipationSettingsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
