<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAddressRequest;
use PagarmeApiSDKLib\Models\CreateCardOptionsRequest;
use PagarmeApiSDKLib\Models\CreateCardRequest;

/**
 * Builder for model CreateCardRequest
 *
 * @see CreateCardRequest
 */
class CreateCardRequestBuilder
{
    /**
     * @var CreateCardRequest
     */
    private $instance;

    private function __construct(CreateCardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Card Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateCardRequest());
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets holder name field.
     *
     * @param string|null $value
     */
    public function holderName(?string $value): self
    {
        $this->instance->setHolderName($value);
        return $this;
    }

    /**
     * Sets exp month field.
     *
     * @param int|null $value
     */
    public function expMonth(?int $value): self
    {
        $this->instance->setExpMonth($value);
        return $this;
    }

    /**
     * Sets exp year field.
     *
     * @param int|null $value
     */
    public function expYear(?int $value): self
    {
        $this->instance->setExpYear($value);
        return $this;
    }

    /**
     * Sets cvv field.
     *
     * @param string|null $value
     */
    public function cvv(?string $value): self
    {
        $this->instance->setCvv($value);
        return $this;
    }

    /**
     * Sets billing address field.
     *
     * @param CreateAddressRequest|null $value
     */
    public function billingAddress(?CreateAddressRequest $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets brand field.
     *
     * @param string|null $value
     */
    public function brand(?string $value): self
    {
        $this->instance->setBrand($value);
        return $this;
    }

    /**
     * Sets billing address id field.
     *
     * @param string|null $value
     */
    public function billingAddressId(?string $value): self
    {
        $this->instance->setBillingAddressId($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets options field.
     *
     * @param CreateCardOptionsRequest|null $value
     */
    public function options(?CreateCardOptionsRequest $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Sets holder document field.
     *
     * @param string|null $value
     */
    public function holderDocument(?string $value): self
    {
        $this->instance->setHolderDocument($value);
        return $this;
    }

    /**
     * Sets private label field.
     *
     * @param bool|null $value
     */
    public function privateLabel(?bool $value): self
    {
        $this->instance->setPrivateLabel($value);
        return $this;
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Initializes a new Create Card Request object.
     */
    public function build(): CreateCardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
