<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateApplePayRequest;
use PagarmeApiSDKLib\Models\CreateCardPaymentContactlessRequest;
use PagarmeApiSDKLib\Models\CreateEmvDecryptRequest;
use PagarmeApiSDKLib\Models\CreateGooglePayRequest;

/**
 * Builder for model CreateCardPaymentContactlessRequest
 *
 * @see CreateCardPaymentContactlessRequest
 */
class CreateCardPaymentContactlessRequestBuilder
{
    /**
     * @var CreateCardPaymentContactlessRequest
     */
    private $instance;

    private function __construct(CreateCardPaymentContactlessRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Card Payment Contactless Request Builder object.
     *
     * @param string $type
     */
    public static function init(string $type): self
    {
        return new self(new CreateCardPaymentContactlessRequest($type));
    }

    /**
     * Sets apple pay field.
     *
     * @param CreateApplePayRequest|null $value
     */
    public function applePay(?CreateApplePayRequest $value): self
    {
        $this->instance->setApplePay($value);
        return $this;
    }

    /**
     * Sets google pay field.
     *
     * @param CreateGooglePayRequest|null $value
     */
    public function googlePay(?CreateGooglePayRequest $value): self
    {
        $this->instance->setGooglePay($value);
        return $this;
    }

    /**
     * Sets emv field.
     *
     * @param CreateEmvDecryptRequest|null $value
     */
    public function emv(?CreateEmvDecryptRequest $value): self
    {
        $this->instance->setEmv($value);
        return $this;
    }

    /**
     * Initializes a new Create Card Payment Contactless Request object.
     */
    public function build(): CreateCardPaymentContactlessRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
