<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateDiscountRequest;
use PagarmeApiSDKLib\Models\CreatePricingSchemeRequest;
use PagarmeApiSDKLib\Models\CreateSubscriptionItemRequest;

/**
 * Builder for model CreateSubscriptionItemRequest
 *
 * @see CreateSubscriptionItemRequest
 */
class CreateSubscriptionItemRequestBuilder
{
    /**
     * @var CreateSubscriptionItemRequest
     */
    private $instance;

    private function __construct(CreateSubscriptionItemRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Subscription Item Request Builder object.
     *
     * @param string $description
     * @param CreatePricingSchemeRequest $pricingScheme
     * @param string $id
     * @param string $planItemId
     * @param CreateDiscountRequest[] $discounts
     * @param string $name
     */
    public static function init(
        string $description,
        CreatePricingSchemeRequest $pricingScheme,
        string $id,
        string $planItemId,
        array $discounts,
        string $name
    ): self {
        return new self(
            new CreateSubscriptionItemRequest($description, $pricingScheme, $id, $planItemId, $discounts, $name)
        );
    }

    /**
     * Sets cycles field.
     *
     * @param int|null $value
     */
    public function cycles(?int $value): self
    {
        $this->instance->setCycles($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets minimum price field.
     *
     * @param int|null $value
     */
    public function minimumPrice(?int $value): self
    {
        $this->instance->setMinimumPrice($value);
        return $this;
    }

    /**
     * Initializes a new Create Subscription Item Request object.
     */
    public function build(): CreateSubscriptionItemRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
