<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCardRequest;
use PagarmeApiSDKLib\Models\CreateVoucherPaymentRequest;

/**
 * Builder for model CreateVoucherPaymentRequest
 *
 * @see CreateVoucherPaymentRequest
 */
class CreateVoucherPaymentRequestBuilder
{
    /**
     * @var CreateVoucherPaymentRequest
     */
    private $instance;

    private function __construct(CreateVoucherPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Voucher Payment Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateVoucherPaymentRequest());
    }

    /**
     * Sets statement descriptor field.
     *
     * @param string|null $value
     */
    public function statementDescriptor(?string $value): self
    {
        $this->instance->setStatementDescriptor($value);
        return $this;
    }

    /**
     * Sets card id field.
     *
     * @param string|null $value
     */
    public function cardId(?string $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets card token field.
     *
     * @param string|null $value
     */
    public function cardToken(?string $value): self
    {
        $this->instance->setCardToken($value);
        return $this;
    }

    /**
     * Sets Card field.
     *
     * @param CreateCardRequest|null $value
     */
    public function card(?CreateCardRequest $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Sets recurrency cycle field.
     *
     * @param string|null $value
     */
    public function recurrencyCycle(?string $value): self
    {
        $this->instance->setRecurrencyCycle($value);
        return $this;
    }

    /**
     * Initializes a new Create Voucher Payment Request object.
     */
    public function build(): CreateVoucherPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
