<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateRegisterInformationAddressRequest;

/**
 * Builder for model CreateRegisterInformationAddressRequest
 *
 * @see CreateRegisterInformationAddressRequest
 */
class CreateRegisterInformationAddressRequestBuilder
{
    /**
     * @var CreateRegisterInformationAddressRequest
     */
    private $instance;

    private function __construct(CreateRegisterInformationAddressRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Register Information Address Request Builder object.
     *
     * @param string $street
     * @param string $complementary
     * @param string $streetNumber
     * @param string $neighborhood
     * @param string $city
     * @param string $state
     * @param string $zipCode
     * @param string $referencePoint
     */
    public static function init(
        string $street,
        string $complementary,
        string $streetNumber,
        string $neighborhood,
        string $city,
        string $state,
        string $zipCode,
        string $referencePoint
    ): self {
        return new self(new CreateRegisterInformationAddressRequest(
            $street,
            $complementary,
            $streetNumber,
            $neighborhood,
            $city,
            $state,
            $zipCode,
            $referencePoint
        ));
    }

    /**
     * Initializes a new Create Register Information Address Request object.
     */
    public function build(): CreateRegisterInformationAddressRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
