<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateSplitOptionsRequest;
use PagarmeApiSDKLib\Models\CreateSplitRequest;

/**
 * Builder for model CreateSplitRequest
 *
 * @see CreateSplitRequest
 */
class CreateSplitRequestBuilder
{
    /**
     * @var CreateSplitRequest
     */
    private $instance;

    private function __construct(CreateSplitRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Split Request Builder object.
     *
     * @param string $type
     * @param int $amount
     * @param string $recipientId
     */
    public static function init(string $type, int $amount, string $recipientId): self
    {
        return new self(new CreateSplitRequest($type, $amount, $recipientId));
    }

    /**
     * Sets options field.
     *
     * @param CreateSplitOptionsRequest|null $value
     */
    public function options(?CreateSplitOptionsRequest $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Sets split rule id field.
     *
     * @param string|null $value
     */
    public function splitRuleId(?string $value): self
    {
        $this->instance->setSplitRuleId($value);
        return $this;
    }

    /**
     * Initializes a new Create Split Request object.
     */
    public function build(): CreateSplitRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
