<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCardTokenRequest;

/**
 * Builder for model CreateCardTokenRequest
 *
 * @see CreateCardTokenRequest
 */
class CreateCardTokenRequestBuilder
{
    /**
     * @var CreateCardTokenRequest
     */
    private $instance;

    private function __construct(CreateCardTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Card Token Request Builder object.
     *
     * @param string $number
     * @param string $holderName
     * @param int $expMonth
     * @param int $expYear
     * @param string $cvv
     * @param string $brand
     * @param string $label
     */
    public static function init(
        string $number,
        string $holderName,
        int $expMonth,
        int $expYear,
        string $cvv,
        string $brand,
        string $label
    ): self {
        return new self(
            new CreateCardTokenRequest($number, $holderName, $expMonth, $expYear, $cvv, $brand, $label)
        );
    }

    /**
     * Initializes a new Create Card Token Request object.
     */
    public function build(): CreateCardTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
