<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAntifraudRequest;
use PagarmeApiSDKLib\Models\CreateChargeRequest;
use PagarmeApiSDKLib\Models\CreateCustomerRequest;
use PagarmeApiSDKLib\Models\CreatePaymentRequest;

/**
 * Builder for model CreateChargeRequest
 *
 * @see CreateChargeRequest
 */
class CreateChargeRequestBuilder
{
    /**
     * @var CreateChargeRequest
     */
    private $instance;

    private function __construct(CreateChargeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Charge Request Builder object.
     *
     * @param int $amount
     * @param CreatePaymentRequest $payment
     * @param string $orderId
     */
    public static function init(int $amount, CreatePaymentRequest $payment, string $orderId): self
    {
        return new self(new CreateChargeRequest($amount, $payment, $orderId));
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Unsets code field.
     */
    public function unsetCode(): self
    {
        $this->instance->unsetCode();
        return $this;
    }

    /**
     * Sets customer id field.
     *
     * @param string|null $value
     */
    public function customerId(?string $value): self
    {
        $this->instance->setCustomerId($value);
        return $this;
    }

    /**
     * Unsets customer id field.
     */
    public function unsetCustomerId(): self
    {
        $this->instance->unsetCustomerId();
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param CreateCustomerRequest|null $value
     */
    public function customer(?CreateCustomerRequest $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Unsets customer field.
     */
    public function unsetCustomer(): self
    {
        $this->instance->unsetCustomer();
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Unsets metadata field.
     */
    public function unsetMetadata(): self
    {
        $this->instance->unsetMetadata();
        return $this;
    }

    /**
     * Sets due at field.
     *
     * @param \DateTime|null $value
     */
    public function dueAt(?\DateTime $value): self
    {
        $this->instance->setDueAt($value);
        return $this;
    }

    /**
     * Unsets due at field.
     */
    public function unsetDueAt(): self
    {
        $this->instance->unsetDueAt();
        return $this;
    }

    /**
     * Sets antifraud field.
     *
     * @param CreateAntifraudRequest|null $value
     */
    public function antifraud(?CreateAntifraudRequest $value): self
    {
        $this->instance->setAntifraud($value);
        return $this;
    }

    /**
     * Unsets antifraud field.
     */
    public function unsetAntifraud(): self
    {
        $this->instance->unsetAntifraud();
        return $this;
    }

    /**
     * Initializes a new Create Charge Request object.
     */
    public function build(): CreateChargeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
