<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAccessTokenRequest;

/**
 * Builder for model CreateAccessTokenRequest
 *
 * @see CreateAccessTokenRequest
 */
class CreateAccessTokenRequestBuilder
{
    /**
     * @var CreateAccessTokenRequest
     */
    private $instance;

    private function __construct(CreateAccessTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Access Token Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateAccessTokenRequest());
    }

    /**
     * Sets expires in field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Initializes a new Create Access Token Request object.
     */
    public function build(): CreateAccessTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
