<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateAddressRequest;

/**
 * Builder for model CreateAddressRequest
 *
 * @see CreateAddressRequest
 */
class CreateAddressRequestBuilder
{
    /**
     * @var CreateAddressRequest
     */
    private $instance;

    private function __construct(CreateAddressRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Address Request Builder object.
     *
     * @param string $street
     * @param string $number
     * @param string $zipCode
     * @param string $neighborhood
     * @param string $city
     * @param string $state
     * @param string $country
     * @param string $complement
     * @param string $line1
     * @param string $line2
     */
    public static function init(
        string $street,
        string $number,
        string $zipCode,
        string $neighborhood,
        string $city,
        string $state,
        string $country,
        string $complement,
        string $line1,
        string $line2
    ): self {
        return new self(new CreateAddressRequest(
            $street,
            $number,
            $zipCode,
            $neighborhood,
            $city,
            $state,
            $country,
            $complement,
            $line1,
            $line2
        ));
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Unsets metadata field.
     */
    public function unsetMetadata(): self
    {
        $this->instance->unsetMetadata();
        return $this;
    }

    /**
     * Initializes a new Create Address Request object.
     */
    public function build(): CreateAddressRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
