<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateGooglePayIntermediateSigningKeyRequest;
use PagarmeApiSDKLib\Models\CreateGooglePayRequest;

/**
 * Builder for model CreateGooglePayRequest
 *
 * @see CreateGooglePayRequest
 */
class CreateGooglePayRequestBuilder
{
    /**
     * @var CreateGooglePayRequest
     */
    private $instance;

    private function __construct(CreateGooglePayRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Google Pay Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateGooglePayRequest());
    }

    /**
     * Sets version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Unsets version field.
     */
    public function unsetVersion(): self
    {
        $this->instance->unsetVersion();
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param string|null $value
     */
    public function data(?string $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Unsets data field.
     */
    public function unsetData(): self
    {
        $this->instance->unsetData();
        return $this;
    }

    /**
     * Sets intermediate signing key field.
     *
     * @param CreateGooglePayIntermediateSigningKeyRequest|null $value
     */
    public function intermediateSigningKey(?CreateGooglePayIntermediateSigningKeyRequest $value): self
    {
        $this->instance->setIntermediateSigningKey($value);
        return $this;
    }

    /**
     * Unsets intermediate signing key field.
     */
    public function unsetIntermediateSigningKey(): self
    {
        $this->instance->unsetIntermediateSigningKey();
        return $this;
    }

    /**
     * Sets signature field.
     *
     * @param string|null $value
     */
    public function signature(?string $value): self
    {
        $this->instance->setSignature($value);
        return $this;
    }

    /**
     * Unsets signature field.
     */
    public function unsetSignature(): self
    {
        $this->instance->unsetSignature();
        return $this;
    }

    /**
     * Sets signed message field.
     *
     * @param string|null $value
     */
    public function signedMessage(?string $value): self
    {
        $this->instance->setSignedMessage($value);
        return $this;
    }

    /**
     * Unsets signed message field.
     */
    public function unsetSignedMessage(): self
    {
        $this->instance->unsetSignedMessage();
        return $this;
    }

    /**
     * Sets merchant identifier field.
     *
     * @param string|null $value
     */
    public function merchantIdentifier(?string $value): self
    {
        $this->instance->setMerchantIdentifier($value);
        return $this;
    }

    /**
     * Unsets merchant identifier field.
     */
    public function unsetMerchantIdentifier(): self
    {
        $this->instance->unsetMerchantIdentifier();
        return $this;
    }

    /**
     * Initializes a new Create Google Pay Request object.
     */
    public function build(): CreateGooglePayRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
