<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreatePixPaymentRequest;
use PagarmeApiSDKLib\Models\PixAdditionalInformation;

/**
 * Builder for model CreatePixPaymentRequest
 *
 * @see CreatePixPaymentRequest
 */
class CreatePixPaymentRequestBuilder
{
    /**
     * @var CreatePixPaymentRequest
     */
    private $instance;

    private function __construct(CreatePixPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Pix Payment Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CreatePixPaymentRequest());
    }

    /**
     * Sets expires at field.
     *
     * @param \DateTime|null $value
     */
    public function expiresAt(?\DateTime $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets expires in field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets additional information field.
     *
     * @param PixAdditionalInformation[]|null $value
     */
    public function additionalInformation(?array $value): self
    {
        $this->instance->setAdditionalInformation($value);
        return $this;
    }

    /**
     * Initializes a new Create Pix Payment Request object.
     */
    public function build(): CreatePixPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
