<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetAnticipationResponse;
use PagarmeApiSDKLib\Models\GetRecipientResponse;

/**
 * Builder for model GetAnticipationResponse
 *
 * @see GetAnticipationResponse
 */
class GetAnticipationResponseBuilder
{
    /**
     * @var GetAnticipationResponse
     */
    private $instance;

    private function __construct(GetAnticipationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Anticipation Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetAnticipationResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets requested amount field.
     *
     * @param int|null $value
     */
    public function requestedAmount(?int $value): self
    {
        $this->instance->setRequestedAmount($value);
        return $this;
    }

    /**
     * Unsets requested amount field.
     */
    public function unsetRequestedAmount(): self
    {
        $this->instance->unsetRequestedAmount();
        return $this;
    }

    /**
     * Sets approved amount field.
     *
     * @param int|null $value
     */
    public function approvedAmount(?int $value): self
    {
        $this->instance->setApprovedAmount($value);
        return $this;
    }

    /**
     * Unsets approved amount field.
     */
    public function unsetApprovedAmount(): self
    {
        $this->instance->unsetApprovedAmount();
        return $this;
    }

    /**
     * Sets recipient field.
     *
     * @param GetRecipientResponse|null $value
     */
    public function recipient(?GetRecipientResponse $value): self
    {
        $this->instance->setRecipient($value);
        return $this;
    }

    /**
     * Unsets recipient field.
     */
    public function unsetRecipient(): self
    {
        $this->instance->unsetRecipient();
        return $this;
    }

    /**
     * Sets pgid field.
     *
     * @param string|null $value
     */
    public function pgid(?string $value): self
    {
        $this->instance->setPgid($value);
        return $this;
    }

    /**
     * Unsets pgid field.
     */
    public function unsetPgid(): self
    {
        $this->instance->unsetPgid();
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Unsets created at field.
     */
    public function unsetCreatedAt(): self
    {
        $this->instance->unsetCreatedAt();
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Unsets updated at field.
     */
    public function unsetUpdatedAt(): self
    {
        $this->instance->unsetUpdatedAt();
        return $this;
    }

    /**
     * Sets payment date field.
     *
     * @param \DateTime|null $value
     */
    public function paymentDate(?\DateTime $value): self
    {
        $this->instance->setPaymentDate($value);
        return $this;
    }

    /**
     * Unsets payment date field.
     */
    public function unsetPaymentDate(): self
    {
        $this->instance->unsetPaymentDate();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Unsets status field.
     */
    public function unsetStatus(): self
    {
        $this->instance->unsetStatus();
        return $this;
    }

    /**
     * Sets timeframe field.
     *
     * @param string|null $value
     */
    public function timeframe(?string $value): self
    {
        $this->instance->setTimeframe($value);
        return $this;
    }

    /**
     * Unsets timeframe field.
     */
    public function unsetTimeframe(): self
    {
        $this->instance->unsetTimeframe();
        return $this;
    }

    /**
     * Initializes a new Get Anticipation Response object.
     */
    public function build(): GetAnticipationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
