<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetAnticipationLimitResponse;
use PagarmeApiSDKLib\Models\GetAnticipationLimitsResponse;

/**
 * Builder for model GetAnticipationLimitsResponse
 *
 * @see GetAnticipationLimitsResponse
 */
class GetAnticipationLimitsResponseBuilder
{
    /**
     * @var GetAnticipationLimitsResponse
     */
    private $instance;

    private function __construct(GetAnticipationLimitsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Anticipation Limits Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetAnticipationLimitsResponse());
    }

    /**
     * Sets max field.
     *
     * @param GetAnticipationLimitResponse|null $value
     */
    public function max(?GetAnticipationLimitResponse $value): self
    {
        $this->instance->setMax($value);
        return $this;
    }

    /**
     * Unsets max field.
     */
    public function unsetMax(): self
    {
        $this->instance->unsetMax();
        return $this;
    }

    /**
     * Sets min field.
     *
     * @param GetAnticipationLimitResponse|null $value
     */
    public function min(?GetAnticipationLimitResponse $value): self
    {
        $this->instance->setMin($value);
        return $this;
    }

    /**
     * Unsets min field.
     */
    public function unsetMin(): self
    {
        $this->instance->unsetMin();
        return $this;
    }

    /**
     * Initializes a new Get Anticipation Limits Response object.
     */
    public function build(): GetAnticipationLimitsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
