<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetAnticipationLimitResponse;

/**
 * Builder for model GetAnticipationLimitResponse
 *
 * @see GetAnticipationLimitResponse
 */
class GetAnticipationLimitResponseBuilder
{
    /**
     * @var GetAnticipationLimitResponse
     */
    private $instance;

    private function __construct(GetAnticipationLimitResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Anticipation Limit Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetAnticipationLimitResponse());
    }

    /**
     * Sets amount field.
     *
     * @param int|null $value
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets anticipation fee field.
     *
     * @param int|null $value
     */
    public function anticipationFee(?int $value): self
    {
        $this->instance->setAnticipationFee($value);
        return $this;
    }

    /**
     * Unsets anticipation fee field.
     */
    public function unsetAnticipationFee(): self
    {
        $this->instance->unsetAnticipationFee();
        return $this;
    }

    /**
     * Initializes a new Get Anticipation Limit Response object.
     */
    public function build(): GetAnticipationLimitResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
