<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetAddressResponse;
use PagarmeApiSDKLib\Models\GetCheckoutBankTransferPaymentResponse;
use PagarmeApiSDKLib\Models\GetCheckoutBoletoPaymentResponse;
use PagarmeApiSDKLib\Models\GetCheckoutCreditCardPaymentResponse;
use PagarmeApiSDKLib\Models\GetCheckoutDebitCardPaymentResponse;
use PagarmeApiSDKLib\Models\GetCheckoutPaymentResponse;
use PagarmeApiSDKLib\Models\GetCheckoutPixPaymentResponse;
use PagarmeApiSDKLib\Models\GetCustomerResponse;
use PagarmeApiSDKLib\Models\GetShippingResponse;

/**
 * Builder for model GetCheckoutPaymentResponse
 *
 * @see GetCheckoutPaymentResponse
 */
class GetCheckoutPaymentResponseBuilder
{
    /**
     * @var GetCheckoutPaymentResponse
     */
    private $instance;

    private function __construct(GetCheckoutPaymentResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Checkout Payment Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetCheckoutPaymentResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param int|null $value
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets default payment method field.
     *
     * @param string|null $value
     */
    public function defaultPaymentMethod(?string $value): self
    {
        $this->instance->setDefaultPaymentMethod($value);
        return $this;
    }

    /**
     * Unsets default payment method field.
     */
    public function unsetDefaultPaymentMethod(): self
    {
        $this->instance->unsetDefaultPaymentMethod();
        return $this;
    }

    /**
     * Sets success url field.
     *
     * @param string|null $value
     */
    public function successUrl(?string $value): self
    {
        $this->instance->setSuccessUrl($value);
        return $this;
    }

    /**
     * Unsets success url field.
     */
    public function unsetSuccessUrl(): self
    {
        $this->instance->unsetSuccessUrl();
        return $this;
    }

    /**
     * Sets payment url field.
     *
     * @param string|null $value
     */
    public function paymentUrl(?string $value): self
    {
        $this->instance->setPaymentUrl($value);
        return $this;
    }

    /**
     * Unsets payment url field.
     */
    public function unsetPaymentUrl(): self
    {
        $this->instance->unsetPaymentUrl();
        return $this;
    }

    /**
     * Sets gateway affiliation id field.
     *
     * @param string|null $value
     */
    public function gatewayAffiliationId(?string $value): self
    {
        $this->instance->setGatewayAffiliationId($value);
        return $this;
    }

    /**
     * Unsets gateway affiliation id field.
     */
    public function unsetGatewayAffiliationId(): self
    {
        $this->instance->unsetGatewayAffiliationId();
        return $this;
    }

    /**
     * Sets accepted payment methods field.
     *
     * @param string[]|null $value
     */
    public function acceptedPaymentMethods(?array $value): self
    {
        $this->instance->setAcceptedPaymentMethods($value);
        return $this;
    }

    /**
     * Unsets accepted payment methods field.
     */
    public function unsetAcceptedPaymentMethods(): self
    {
        $this->instance->unsetAcceptedPaymentMethods();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Unsets status field.
     */
    public function unsetStatus(): self
    {
        $this->instance->unsetStatus();
        return $this;
    }

    /**
     * Sets skip checkout success page field.
     *
     * @param bool|null $value
     */
    public function skipCheckoutSuccessPage(?bool $value): self
    {
        $this->instance->setSkipCheckoutSuccessPage($value);
        return $this;
    }

    /**
     * Unsets skip checkout success page field.
     */
    public function unsetSkipCheckoutSuccessPage(): self
    {
        $this->instance->unsetSkipCheckoutSuccessPage();
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Unsets created at field.
     */
    public function unsetCreatedAt(): self
    {
        $this->instance->unsetCreatedAt();
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Unsets updated at field.
     */
    public function unsetUpdatedAt(): self
    {
        $this->instance->unsetUpdatedAt();
        return $this;
    }

    /**
     * Sets canceled at field.
     *
     * @param \DateTime|null $value
     */
    public function canceledAt(?\DateTime $value): self
    {
        $this->instance->setCanceledAt($value);
        return $this;
    }

    /**
     * Unsets canceled at field.
     */
    public function unsetCanceledAt(): self
    {
        $this->instance->unsetCanceledAt();
        return $this;
    }

    /**
     * Sets customer editable field.
     *
     * @param bool|null $value
     */
    public function customerEditable(?bool $value): self
    {
        $this->instance->setCustomerEditable($value);
        return $this;
    }

    /**
     * Unsets customer editable field.
     */
    public function unsetCustomerEditable(): self
    {
        $this->instance->unsetCustomerEditable();
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param GetCustomerResponse|null $value
     */
    public function customer(?GetCustomerResponse $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Unsets customer field.
     */
    public function unsetCustomer(): self
    {
        $this->instance->unsetCustomer();
        return $this;
    }

    /**
     * Sets billingaddress field.
     *
     * @param GetAddressResponse|null $value
     */
    public function billingaddress(?GetAddressResponse $value): self
    {
        $this->instance->setBillingaddress($value);
        return $this;
    }

    /**
     * Unsets billingaddress field.
     */
    public function unsetBillingaddress(): self
    {
        $this->instance->unsetBillingaddress();
        return $this;
    }

    /**
     * Sets credit card field.
     *
     * @param GetCheckoutCreditCardPaymentResponse|null $value
     */
    public function creditCard(?GetCheckoutCreditCardPaymentResponse $value): self
    {
        $this->instance->setCreditCard($value);
        return $this;
    }

    /**
     * Unsets credit card field.
     */
    public function unsetCreditCard(): self
    {
        $this->instance->unsetCreditCard();
        return $this;
    }

    /**
     * Sets boleto field.
     *
     * @param GetCheckoutBoletoPaymentResponse|null $value
     */
    public function boleto(?GetCheckoutBoletoPaymentResponse $value): self
    {
        $this->instance->setBoleto($value);
        return $this;
    }

    /**
     * Unsets boleto field.
     */
    public function unsetBoleto(): self
    {
        $this->instance->unsetBoleto();
        return $this;
    }

    /**
     * Sets billing address editable field.
     *
     * @param bool|null $value
     */
    public function billingAddressEditable(?bool $value): self
    {
        $this->instance->setBillingAddressEditable($value);
        return $this;
    }

    /**
     * Unsets billing address editable field.
     */
    public function unsetBillingAddressEditable(): self
    {
        $this->instance->unsetBillingAddressEditable();
        return $this;
    }

    /**
     * Sets shipping field.
     *
     * @param GetShippingResponse|null $value
     */
    public function shipping(?GetShippingResponse $value): self
    {
        $this->instance->setShipping($value);
        return $this;
    }

    /**
     * Unsets shipping field.
     */
    public function unsetShipping(): self
    {
        $this->instance->unsetShipping();
        return $this;
    }

    /**
     * Sets shippable field.
     *
     * @param bool|null $value
     */
    public function shippable(?bool $value): self
    {
        $this->instance->setShippable($value);
        return $this;
    }

    /**
     * Unsets shippable field.
     */
    public function unsetShippable(): self
    {
        $this->instance->unsetShippable();
        return $this;
    }

    /**
     * Sets closed at field.
     *
     * @param \DateTime|null $value
     */
    public function closedAt(?\DateTime $value): self
    {
        $this->instance->setClosedAt($value);
        return $this;
    }

    /**
     * Unsets closed at field.
     */
    public function unsetClosedAt(): self
    {
        $this->instance->unsetClosedAt();
        return $this;
    }

    /**
     * Sets expires at field.
     *
     * @param \DateTime|null $value
     */
    public function expiresAt(?\DateTime $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Unsets expires at field.
     */
    public function unsetExpiresAt(): self
    {
        $this->instance->unsetExpiresAt();
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Unsets currency field.
     */
    public function unsetCurrency(): self
    {
        $this->instance->unsetCurrency();
        return $this;
    }

    /**
     * Sets debit card field.
     *
     * @param GetCheckoutDebitCardPaymentResponse|null $value
     */
    public function debitCard(?GetCheckoutDebitCardPaymentResponse $value): self
    {
        $this->instance->setDebitCard($value);
        return $this;
    }

    /**
     * Unsets debit card field.
     */
    public function unsetDebitCard(): self
    {
        $this->instance->unsetDebitCard();
        return $this;
    }

    /**
     * Sets bank transfer field.
     *
     * @param GetCheckoutBankTransferPaymentResponse|null $value
     */
    public function bankTransfer(?GetCheckoutBankTransferPaymentResponse $value): self
    {
        $this->instance->setBankTransfer($value);
        return $this;
    }

    /**
     * Unsets bank transfer field.
     */
    public function unsetBankTransfer(): self
    {
        $this->instance->unsetBankTransfer();
        return $this;
    }

    /**
     * Sets accepted brands field.
     *
     * @param string[]|null $value
     */
    public function acceptedBrands(?array $value): self
    {
        $this->instance->setAcceptedBrands($value);
        return $this;
    }

    /**
     * Unsets accepted brands field.
     */
    public function unsetAcceptedBrands(): self
    {
        $this->instance->unsetAcceptedBrands();
        return $this;
    }

    /**
     * Sets pix field.
     *
     * @param GetCheckoutPixPaymentResponse|null $value
     */
    public function pix(?GetCheckoutPixPaymentResponse $value): self
    {
        $this->instance->setPix($value);
        return $this;
    }

    /**
     * Unsets pix field.
     */
    public function unsetPix(): self
    {
        $this->instance->unsetPix();
        return $this;
    }

    /**
     * Initializes a new Get Checkout Payment Response object.
     */
    public function build(): GetCheckoutPaymentResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
