<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetChargesSummaryResponse;

/**
 * Builder for model GetChargesSummaryResponse
 *
 * @see GetChargesSummaryResponse
 */
class GetChargesSummaryResponseBuilder
{
    /**
     * @var GetChargesSummaryResponse
     */
    private $instance;

    private function __construct(GetChargesSummaryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Charges Summary Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetChargesSummaryResponse());
    }

    /**
     * Sets total field.
     *
     * @param int|null $value
     */
    public function total(?int $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Unsets total field.
     */
    public function unsetTotal(): self
    {
        $this->instance->unsetTotal();
        return $this;
    }

    /**
     * Initializes a new Get Charges Summary Response object.
     */
    public function build(): GetChargesSummaryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
