<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetCheckoutBoletoPaymentResponse;

/**
 * Builder for model GetCheckoutBoletoPaymentResponse
 *
 * @see GetCheckoutBoletoPaymentResponse
 */
class GetCheckoutBoletoPaymentResponseBuilder
{
    /**
     * @var GetCheckoutBoletoPaymentResponse
     */
    private $instance;

    private function __construct(GetCheckoutBoletoPaymentResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Checkout Boleto Payment Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetCheckoutBoletoPaymentResponse());
    }

    /**
     * Sets due at field.
     *
     * @param \DateTime|null $value
     */
    public function dueAt(?\DateTime $value): self
    {
        $this->instance->setDueAt($value);
        return $this;
    }

    /**
     * Unsets due at field.
     */
    public function unsetDueAt(): self
    {
        $this->instance->unsetDueAt();
        return $this;
    }

    /**
     * Sets instructions field.
     *
     * @param string|null $value
     */
    public function instructions(?string $value): self
    {
        $this->instance->setInstructions($value);
        return $this;
    }

    /**
     * Unsets instructions field.
     */
    public function unsetInstructions(): self
    {
        $this->instance->unsetInstructions();
        return $this;
    }

    /**
     * Initializes a new Get Checkout Boleto Payment Response object.
     */
    public function build(): GetCheckoutBoletoPaymentResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
