<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetDeviceResponse;

/**
 * Builder for model GetDeviceResponse
 *
 * @see GetDeviceResponse
 */
class GetDeviceResponseBuilder
{
    /**
     * @var GetDeviceResponse
     */
    private $instance;

    private function __construct(GetDeviceResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Device Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetDeviceResponse());
    }

    /**
     * Sets platform field.
     *
     * @param string|null $value
     */
    public function platform(?string $value): self
    {
        $this->instance->setPlatform($value);
        return $this;
    }

    /**
     * Unsets platform field.
     */
    public function unsetPlatform(): self
    {
        $this->instance->unsetPlatform();
        return $this;
    }

    /**
     * Initializes a new Get Device Response object.
     */
    public function build(): GetDeviceResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
