<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetGatewayErrorResponse;

/**
 * Builder for model GetGatewayErrorResponse
 *
 * @see GetGatewayErrorResponse
 */
class GetGatewayErrorResponseBuilder
{
    /**
     * @var GetGatewayErrorResponse
     */
    private $instance;

    private function __construct(GetGatewayErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Gateway Error Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetGatewayErrorResponse());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Unsets message field.
     */
    public function unsetMessage(): self
    {
        $this->instance->unsetMessage();
        return $this;
    }

    /**
     * Initializes a new Get Gateway Error Response object.
     */
    public function build(): GetGatewayErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
