<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetMovementObjectTransferResponse;

/**
 * Builder for model GetMovementObjectTransferResponse
 *
 * @see GetMovementObjectTransferResponse
 */
class GetMovementObjectTransferResponseBuilder
{
    /**
     * @var GetMovementObjectTransferResponse
     */
    private $instance;

    private function __construct(GetMovementObjectTransferResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Movement Object Transfer Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetMovementObjectTransferResponse());
    }

    /**
     * Sets object field.
     *
     * @param string|null $value
     */
    public function object(?string $value): self
    {
        $this->instance->setObject($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Unsets status field.
     */
    public function unsetStatus(): self
    {
        $this->instance->unsetStatus();
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param string|null $value
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Unsets created at field.
     */
    public function unsetCreatedAt(): self
    {
        $this->instance->unsetCreatedAt();
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Sets charge id field.
     *
     * @param string|null $value
     */
    public function chargeId(?string $value): self
    {
        $this->instance->setChargeId($value);
        return $this;
    }

    /**
     * Unsets charge id field.
     */
    public function unsetChargeId(): self
    {
        $this->instance->unsetChargeId();
        return $this;
    }

    /**
     * Sets gateway id field.
     *
     * @param string|null $value
     */
    public function gatewayId(?string $value): self
    {
        $this->instance->setGatewayId($value);
        return $this;
    }

    /**
     * Unsets gateway id field.
     */
    public function unsetGatewayId(): self
    {
        $this->instance->unsetGatewayId();
        return $this;
    }

    /**
     * Sets source type field.
     *
     * @param string|null $value
     */
    public function sourceType(?string $value): self
    {
        $this->instance->setSourceType($value);
        return $this;
    }

    /**
     * Unsets source type field.
     */
    public function unsetSourceType(): self
    {
        $this->instance->unsetSourceType();
        return $this;
    }

    /**
     * Sets source id field.
     *
     * @param string|null $value
     */
    public function sourceId(?string $value): self
    {
        $this->instance->setSourceId($value);
        return $this;
    }

    /**
     * Unsets source id field.
     */
    public function unsetSourceId(): self
    {
        $this->instance->unsetSourceId();
        return $this;
    }

    /**
     * Sets target type field.
     *
     * @param string|null $value
     */
    public function targetType(?string $value): self
    {
        $this->instance->setTargetType($value);
        return $this;
    }

    /**
     * Unsets target type field.
     */
    public function unsetTargetType(): self
    {
        $this->instance->unsetTargetType();
        return $this;
    }

    /**
     * Sets target id field.
     *
     * @param string|null $value
     */
    public function targetId(?string $value): self
    {
        $this->instance->setTargetId($value);
        return $this;
    }

    /**
     * Unsets target id field.
     */
    public function unsetTargetId(): self
    {
        $this->instance->unsetTargetId();
        return $this;
    }

    /**
     * Sets fee field.
     *
     * @param string|null $value
     */
    public function fee(?string $value): self
    {
        $this->instance->setFee($value);
        return $this;
    }

    /**
     * Unsets fee field.
     */
    public function unsetFee(): self
    {
        $this->instance->unsetFee();
        return $this;
    }

    /**
     * Sets funding date field.
     *
     * @param string|null $value
     */
    public function fundingDate(?string $value): self
    {
        $this->instance->setFundingDate($value);
        return $this;
    }

    /**
     * Unsets funding date field.
     */
    public function unsetFundingDate(): self
    {
        $this->instance->unsetFundingDate();
        return $this;
    }

    /**
     * Sets funding estimated date field.
     *
     * @param string|null $value
     */
    public function fundingEstimatedDate(?string $value): self
    {
        $this->instance->setFundingEstimatedDate($value);
        return $this;
    }

    /**
     * Unsets funding estimated date field.
     */
    public function unsetFundingEstimatedDate(): self
    {
        $this->instance->unsetFundingEstimatedDate();
        return $this;
    }

    /**
     * Sets bank account field.
     *
     * @param string|null $value
     */
    public function bankAccount(?string $value): self
    {
        $this->instance->setBankAccount($value);
        return $this;
    }

    /**
     * Unsets bank account field.
     */
    public function unsetBankAccount(): self
    {
        $this->instance->unsetBankAccount();
        return $this;
    }

    /**
     * Initializes a new Get Movement Object Transfer Response object.
     */
    public function build(): GetMovementObjectTransferResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
