<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetMovementObjectFeeCollectionResponse;

/**
 * Builder for model GetMovementObjectFeeCollectionResponse
 *
 * @see GetMovementObjectFeeCollectionResponse
 */
class GetMovementObjectFeeCollectionResponseBuilder
{
    /**
     * @var GetMovementObjectFeeCollectionResponse
     */
    private $instance;

    private function __construct(GetMovementObjectFeeCollectionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Movement Object Fee Collection Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetMovementObjectFeeCollectionResponse());
    }

    /**
     * Sets object field.
     *
     * @param string|null $value
     */
    public function object(?string $value): self
    {
        $this->instance->setObject($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Unsets status field.
     */
    public function unsetStatus(): self
    {
        $this->instance->unsetStatus();
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param string|null $value
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Unsets created at field.
     */
    public function unsetCreatedAt(): self
    {
        $this->instance->unsetCreatedAt();
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Sets charge id field.
     *
     * @param string|null $value
     */
    public function chargeId(?string $value): self
    {
        $this->instance->setChargeId($value);
        return $this;
    }

    /**
     * Unsets charge id field.
     */
    public function unsetChargeId(): self
    {
        $this->instance->unsetChargeId();
        return $this;
    }

    /**
     * Sets gateway id field.
     *
     * @param string|null $value
     */
    public function gatewayId(?string $value): self
    {
        $this->instance->setGatewayId($value);
        return $this;
    }

    /**
     * Unsets gateway id field.
     */
    public function unsetGatewayId(): self
    {
        $this->instance->unsetGatewayId();
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets payment date field.
     *
     * @param string|null $value
     */
    public function paymentDate(?string $value): self
    {
        $this->instance->setPaymentDate($value);
        return $this;
    }

    /**
     * Unsets payment date field.
     */
    public function unsetPaymentDate(): self
    {
        $this->instance->unsetPaymentDate();
        return $this;
    }

    /**
     * Sets recipient id field.
     *
     * @param string|null $value
     */
    public function recipientId(?string $value): self
    {
        $this->instance->setRecipientId($value);
        return $this;
    }

    /**
     * Unsets recipient id field.
     */
    public function unsetRecipientId(): self
    {
        $this->instance->unsetRecipientId();
        return $this;
    }

    /**
     * Initializes a new Get Movement Object Fee Collection Response object.
     */
    public function build(): GetMovementObjectFeeCollectionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
