<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetPixBankAccountResponse;

/**
 * Builder for model GetPixBankAccountResponse
 *
 * @see GetPixBankAccountResponse
 */
class GetPixBankAccountResponseBuilder
{
    /**
     * @var GetPixBankAccountResponse
     */
    private $instance;

    private function __construct(GetPixBankAccountResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Pix Bank Account Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetPixBankAccountResponse());
    }

    /**
     * Sets bank name field.
     *
     * @param string|null $value
     */
    public function bankName(?string $value): self
    {
        $this->instance->setBankName($value);
        return $this;
    }

    /**
     * Unsets bank name field.
     */
    public function unsetBankName(): self
    {
        $this->instance->unsetBankName();
        return $this;
    }

    /**
     * Sets ispb field.
     *
     * @param string|null $value
     */
    public function ispb(?string $value): self
    {
        $this->instance->setIspb($value);
        return $this;
    }

    /**
     * Unsets ispb field.
     */
    public function unsetIspb(): self
    {
        $this->instance->unsetIspb();
        return $this;
    }

    /**
     * Sets branch code field.
     *
     * @param string|null $value
     */
    public function branchCode(?string $value): self
    {
        $this->instance->setBranchCode($value);
        return $this;
    }

    /**
     * Unsets branch code field.
     */
    public function unsetBranchCode(): self
    {
        $this->instance->unsetBranchCode();
        return $this;
    }

    /**
     * Sets account number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets account number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Initializes a new Get Pix Bank Account Response object.
     */
    public function build(): GetPixBankAccountResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
