<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetPhoneNumberResponse;

/**
 * Builder for model GetPhoneNumberResponse
 *
 * @see GetPhoneNumberResponse
 */
class GetPhoneNumberResponseBuilder
{
    /**
     * @var GetPhoneNumberResponse
     */
    private $instance;

    private function __construct(GetPhoneNumberResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Phone Number Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetPhoneNumberResponse());
    }

    /**
     * Sets ddd field.
     *
     * @param string|null $value
     */
    public function ddd(?string $value): self
    {
        $this->instance->setDdd($value);
        return $this;
    }

    /**
     * Unsets ddd field.
     */
    public function unsetDdd(): self
    {
        $this->instance->unsetDdd();
        return $this;
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Unsets number field.
     */
    public function unsetNumber(): self
    {
        $this->instance->unsetNumber();
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Initializes a new Get Phone Number Response object.
     */
    public function build(): GetPhoneNumberResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
