<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetInvoiceResponse;
use PagarmeApiSDKLib\Models\ListInvoicesResponse;
use PagarmeApiSDKLib\Models\PagingResponse;

/**
 * Builder for model ListInvoicesResponse
 *
 * @see ListInvoicesResponse
 */
class ListInvoicesResponseBuilder
{
    /**
     * @var ListInvoicesResponse
     */
    private $instance;

    private function __construct(ListInvoicesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Invoices Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListInvoicesResponse());
    }

    /**
     * Sets data field.
     *
     * @param GetInvoiceResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Unsets data field.
     */
    public function unsetData(): self
    {
        $this->instance->unsetData();
        return $this;
    }

    /**
     * Sets paging field.
     *
     * @param PagingResponse|null $value
     */
    public function paging(?PagingResponse $value): self
    {
        $this->instance->setPaging($value);
        return $this;
    }

    /**
     * Unsets paging field.
     */
    public function unsetPaging(): self
    {
        $this->instance->unsetPaging();
        return $this;
    }

    /**
     * Initializes a new List Invoices Response object.
     */
    public function build(): ListInvoicesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
