<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetPayableResponse;
use PagarmeApiSDKLib\Models\ListPayablesResponse;
use PagarmeApiSDKLib\Models\PagingResponse;

/**
 * Builder for model ListPayablesResponse
 *
 * @see ListPayablesResponse
 */
class ListPayablesResponseBuilder
{
    /**
     * @var ListPayablesResponse
     */
    private $instance;

    private function __construct(ListPayablesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Payables Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListPayablesResponse());
    }

    /**
     * Sets data field.
     *
     * @param GetPayableResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Unsets data field.
     */
    public function unsetData(): self
    {
        $this->instance->unsetData();
        return $this;
    }

    /**
     * Sets paging field.
     *
     * @param PagingResponse|null $value
     */
    public function paging(?PagingResponse $value): self
    {
        $this->instance->setPaging($value);
        return $this;
    }

    /**
     * Unsets paging field.
     */
    public function unsetPaging(): self
    {
        $this->instance->unsetPaging();
        return $this;
    }

    /**
     * Initializes a new List Payables Response object.
     */
    public function build(): ListPayablesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
