<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\GetTransfer;
use PagarmeApiSDKLib\Models\ListTransfers;
use PagarmeApiSDKLib\Models\PagingResponse;

/**
 * Builder for model ListTransfers
 *
 * @see ListTransfers
 */
class ListTransfersBuilder
{
    /**
     * @var ListTransfers
     */
    private $instance;

    private function __construct(ListTransfers $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Transfers Builder object.
     *
     * @param GetTransfer[] $data
     * @param PagingResponse $paging
     */
    public static function init(array $data, PagingResponse $paging): self
    {
        return new self(new ListTransfers($data, $paging));
    }

    /**
     * Initializes a new List Transfers object.
     */
    public function build(): ListTransfers
    {
        return CoreHelper::clone($this->instance);
    }
}
