<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\PagingResponse;

/**
 * Builder for model PagingResponse
 *
 * @see PagingResponse
 */
class PagingResponseBuilder
{
    /**
     * @var PagingResponse
     */
    private $instance;

    private function __construct(PagingResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paging Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PagingResponse());
    }

    /**
     * Sets total field.
     *
     * @param int|null $value
     */
    public function total(?int $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Unsets total field.
     */
    public function unsetTotal(): self
    {
        $this->instance->unsetTotal();
        return $this;
    }

    /**
     * Sets previous field.
     *
     * @param string|null $value
     */
    public function previous(?string $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Unsets previous field.
     */
    public function unsetPrevious(): self
    {
        $this->instance->unsetPrevious();
        return $this;
    }

    /**
     * Sets next field.
     *
     * @param string|null $value
     */
    public function next(?string $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Unsets next field.
     */
    public function unsetNext(): self
    {
        $this->instance->unsetNext();
        return $this;
    }

    /**
     * Initializes a new Paging Response object.
     */
    public function build(): PagingResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
