<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\PixAdditionalInformation;

/**
 * Builder for model PixAdditionalInformation
 *
 * @see PixAdditionalInformation
 */
class PixAdditionalInformationBuilder
{
    /**
     * @var PixAdditionalInformation
     */
    private $instance;

    private function __construct(PixAdditionalInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pix Additional Information Builder object.
     */
    public static function init(): self
    {
        return new self(new PixAdditionalInformation());
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Unsets Name field.
     */
    public function unsetName(): self
    {
        $this->instance->unsetName();
        return $this;
    }

    /**
     * Sets Value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Unsets Value field.
     */
    public function unsetValue(): self
    {
        $this->instance->unsetValue();
        return $this;
    }

    /**
     * Initializes a new Pix Additional Information object.
     */
    public function build(): PixAdditionalInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
