<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateBankTransferPaymentRequest;
use PagarmeApiSDKLib\Models\CreateBoletoPaymentRequest;
use PagarmeApiSDKLib\Models\CreateCashPaymentRequest;
use PagarmeApiSDKLib\Models\CreateCreditCardPaymentRequest;
use PagarmeApiSDKLib\Models\CreateDebitCardPaymentRequest;
use PagarmeApiSDKLib\Models\CreatePrivateLabelPaymentRequest;
use PagarmeApiSDKLib\Models\CreateVoucherPaymentRequest;
use PagarmeApiSDKLib\Models\UpdateChargePaymentMethodRequest;

/**
 * Builder for model UpdateChargePaymentMethodRequest
 *
 * @see UpdateChargePaymentMethodRequest
 */
class UpdateChargePaymentMethodRequestBuilder
{
    /**
     * @var UpdateChargePaymentMethodRequest
     */
    private $instance;

    private function __construct(UpdateChargePaymentMethodRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Charge Payment Method Request Builder object.
     *
     * @param bool $updateSubscription
     * @param string $paymentMethod
     * @param CreateCreditCardPaymentRequest $creditCard
     * @param CreateDebitCardPaymentRequest $debitCard
     * @param CreateBoletoPaymentRequest $boleto
     * @param CreateVoucherPaymentRequest $voucher
     * @param CreateCashPaymentRequest $cash
     * @param CreateBankTransferPaymentRequest $bankTransfer
     * @param CreatePrivateLabelPaymentRequest $privateLabel
     */
    public static function init(
        bool $updateSubscription,
        string $paymentMethod,
        CreateCreditCardPaymentRequest $creditCard,
        CreateDebitCardPaymentRequest $debitCard,
        CreateBoletoPaymentRequest $boleto,
        CreateVoucherPaymentRequest $voucher,
        CreateCashPaymentRequest $cash,
        CreateBankTransferPaymentRequest $bankTransfer,
        CreatePrivateLabelPaymentRequest $privateLabel
    ): self {
        return new self(new UpdateChargePaymentMethodRequest(
            $updateSubscription,
            $paymentMethod,
            $creditCard,
            $debitCard,
            $boleto,
            $voucher,
            $cash,
            $bankTransfer,
            $privateLabel
        ));
    }

    /**
     * Initializes a new Update Charge Payment Method Request object.
     */
    public function build(): UpdateChargePaymentMethodRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
