<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\UpdateAutomaticAnticipationSettingsRequest;

/**
 * Builder for model UpdateAutomaticAnticipationSettingsRequest
 *
 * @see UpdateAutomaticAnticipationSettingsRequest
 */
class UpdateAutomaticAnticipationSettingsRequestBuilder
{
    /**
     * @var UpdateAutomaticAnticipationSettingsRequest
     */
    private $instance;

    private function __construct(UpdateAutomaticAnticipationSettingsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Automatic Anticipation Settings Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateAutomaticAnticipationSettingsRequest());
    }

    /**
     * Sets enabled field.
     *
     * @param bool|null $value
     */
    public function enabled(?bool $value): self
    {
        $this->instance->setEnabled($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets volume percentage field.
     *
     * @param int|null $value
     */
    public function volumePercentage(?int $value): self
    {
        $this->instance->setVolumePercentage($value);
        return $this;
    }

    /**
     * Sets delay field.
     *
     * @param int|null $value
     */
    public function delay(?int $value): self
    {
        $this->instance->setDelay($value);
        return $this;
    }

    /**
     * Sets days field.
     *
     * @param int|null $value
     */
    public function days(?int $value): self
    {
        $this->instance->setDays($value);
        return $this;
    }

    /**
     * Initializes a new Update Automatic Anticipation Settings Request object.
     */
    public function build(): UpdateAutomaticAnticipationSettingsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
