<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models\Builders;

use Core\Utils\CoreHelper;
use PagarmeApiSDKLib\Models\CreateCardRequest;
use PagarmeApiSDKLib\Models\UpdateSubscriptionCardRequest;

/**
 * Builder for model UpdateSubscriptionCardRequest
 *
 * @see UpdateSubscriptionCardRequest
 */
class UpdateSubscriptionCardRequestBuilder
{
    /**
     * @var UpdateSubscriptionCardRequest
     */
    private $instance;

    private function __construct(UpdateSubscriptionCardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Subscription Card Request Builder object.
     *
     * @param CreateCardRequest $card
     * @param string $cardId
     */
    public static function init(CreateCardRequest $card, string $cardId): self
    {
        return new self(new UpdateSubscriptionCardRequest($card, $cardId));
    }

    /**
     * Sets indirect acceptor field.
     *
     * @param string|null $value
     */
    public function indirectAcceptor(?string $value): self
    {
        $this->instance->setIndirectAcceptor($value);
        return $this;
    }

    /**
     * Initializes a new Update Subscription Card Request object.
     */
    public function build(): UpdateSubscriptionCardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
