<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Card data
 */
class CreateCardRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $number;

    /**
     * @var string|null
     */
    private $holderName;

    /**
     * @var int|null
     */
    private $expMonth;

    /**
     * @var int|null
     */
    private $expYear;

    /**
     * @var string|null
     */
    private $cvv;

    /**
     * @var CreateAddressRequest|null
     */
    private $billingAddress;

    /**
     * @var string|null
     */
    private $brand;

    /**
     * @var string|null
     */
    private $billingAddressId;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var string|null
     */
    private $type = 'credit';

    /**
     * @var CreateCardOptionsRequest|null
     */
    private $options;

    /**
     * @var string|null
     */
    private $holderDocument;

    /**
     * @var bool|null
     */
    private $privateLabel;

    /**
     * @var string|null
     */
    private $label;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $token;

    /**
     * Returns Number.
     * Credit card number
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * Sets Number.
     * Credit card number
     *
     * @maps number
     */
    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }

    /**
     * Returns Holder Name.
     * Holder name, as written on the card
     */
    public function getHolderName(): ?string
    {
        return $this->holderName;
    }

    /**
     * Sets Holder Name.
     * Holder name, as written on the card
     *
     * @maps holder_name
     */
    public function setHolderName(?string $holderName): void
    {
        $this->holderName = $holderName;
    }

    /**
     * Returns Exp Month.
     * The expiration month
     */
    public function getExpMonth(): ?int
    {
        return $this->expMonth;
    }

    /**
     * Sets Exp Month.
     * The expiration month
     *
     * @maps exp_month
     */
    public function setExpMonth(?int $expMonth): void
    {
        $this->expMonth = $expMonth;
    }

    /**
     * Returns Exp Year.
     * The expiration year, that can be informed with 2 or 4 digits
     */
    public function getExpYear(): ?int
    {
        return $this->expYear;
    }

    /**
     * Sets Exp Year.
     * The expiration year, that can be informed with 2 or 4 digits
     *
     * @maps exp_year
     */
    public function setExpYear(?int $expYear): void
    {
        $this->expYear = $expYear;
    }

    /**
     * Returns Cvv.
     * The card's security code
     */
    public function getCvv(): ?string
    {
        return $this->cvv;
    }

    /**
     * Sets Cvv.
     * The card's security code
     *
     * @maps cvv
     */
    public function setCvv(?string $cvv): void
    {
        $this->cvv = $cvv;
    }

    /**
     * Returns Billing Address.
     * Card's billing address
     */
    public function getBillingAddress(): ?CreateAddressRequest
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     * Card's billing address
     *
     * @maps billing_address
     */
    public function setBillingAddress(?CreateAddressRequest $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Brand.
     * Card brand
     */
    public function getBrand(): ?string
    {
        return $this->brand;
    }

    /**
     * Sets Brand.
     * Card brand
     *
     * @maps brand
     */
    public function setBrand(?string $brand): void
    {
        $this->brand = $brand;
    }

    /**
     * Returns Billing Address Id.
     * The address id for the billing address
     */
    public function getBillingAddressId(): ?string
    {
        return $this->billingAddressId;
    }

    /**
     * Sets Billing Address Id.
     * The address id for the billing address
     *
     * @maps billing_address_id
     */
    public function setBillingAddressId(?string $billingAddressId): void
    {
        $this->billingAddressId = $billingAddressId;
    }

    /**
     * Returns Metadata.
     * Metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * Metadata
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Type.
     * Card type
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Card type
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Options.
     * Options for creating the card
     */
    public function getOptions(): ?CreateCardOptionsRequest
    {
        return $this->options;
    }

    /**
     * Sets Options.
     * Options for creating the card
     *
     * @maps options
     */
    public function setOptions(?CreateCardOptionsRequest $options): void
    {
        $this->options = $options;
    }

    /**
     * Returns Holder Document.
     * Document number for the card's holder
     */
    public function getHolderDocument(): ?string
    {
        return $this->holderDocument;
    }

    /**
     * Sets Holder Document.
     * Document number for the card's holder
     *
     * @maps holder_document
     */
    public function setHolderDocument(?string $holderDocument): void
    {
        $this->holderDocument = $holderDocument;
    }

    /**
     * Returns Private Label.
     * Indicates whether it is a private label card
     */
    public function getPrivateLabel(): ?bool
    {
        return $this->privateLabel;
    }

    /**
     * Sets Private Label.
     * Indicates whether it is a private label card
     *
     * @maps private_label
     */
    public function setPrivateLabel(?bool $privateLabel): void
    {
        $this->privateLabel = $privateLabel;
    }

    /**
     * Returns Label.
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     *
     * @maps label
     */
    public function setLabel(?string $label): void
    {
        $this->label = $label;
    }

    /**
     * Returns Id.
     * Identifier
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Identifier
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Token.
     * token identifier
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * token identifier
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Converts the CreateCardRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateCardRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateCardRequest',
            [
                'number' => $this->number,
                'holderName' => $this->holderName,
                'expMonth' => $this->expMonth,
                'expYear' => $this->expYear,
                'cvv' => $this->cvv,
                'billingAddress' => $this->billingAddress,
                'brand' => $this->brand,
                'billingAddressId' => $this->billingAddressId,
                'metadata' => $this->metadata,
                'type' => $this->type,
                'options' => $this->options,
                'holderDocument' => $this->holderDocument,
                'privateLabel' => $this->privateLabel,
                'label' => $this->label,
                'id' => $this->id,
                'token' => $this->token
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->number)) {
            $json['number']             = $this->number;
        }
        if (isset($this->holderName)) {
            $json['holder_name']        = $this->holderName;
        }
        if (isset($this->expMonth)) {
            $json['exp_month']          = $this->expMonth;
        }
        if (isset($this->expYear)) {
            $json['exp_year']           = $this->expYear;
        }
        if (isset($this->cvv)) {
            $json['cvv']                = $this->cvv;
        }
        if (isset($this->billingAddress)) {
            $json['billing_address']    = $this->billingAddress;
        }
        if (isset($this->brand)) {
            $json['brand']              = $this->brand;
        }
        if (isset($this->billingAddressId)) {
            $json['billing_address_id'] = $this->billingAddressId;
        }
        if (isset($this->metadata)) {
            $json['metadata']           = $this->metadata;
        }
        if (isset($this->type)) {
            $json['type']               = $this->type;
        }
        if (isset($this->options)) {
            $json['options']            = $this->options;
        }
        if (isset($this->holderDocument)) {
            $json['holder_document']    = $this->holderDocument;
        }
        if (isset($this->privateLabel)) {
            $json['private_label']      = $this->privateLabel;
        }
        if (isset($this->label)) {
            $json['label']              = $this->label;
        }
        if (isset($this->id)) {
            $json['id']                 = $this->id;
        }
        if (isset($this->token)) {
            $json['token']              = $this->token;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
