<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

class CreatePhonesRequest implements \JsonSerializable
{
    /**
     * @var CreatePhoneRequest|null
     */
    private $homePhone;

    /**
     * @var CreatePhoneRequest|null
     */
    private $mobilePhone;

    /**
     * Returns Home Phone.
     */
    public function getHomePhone(): ?CreatePhoneRequest
    {
        return $this->homePhone;
    }

    /**
     * Sets Home Phone.
     *
     * @maps home_phone
     */
    public function setHomePhone(?CreatePhoneRequest $homePhone): void
    {
        $this->homePhone = $homePhone;
    }

    /**
     * Returns Mobile Phone.
     */
    public function getMobilePhone(): ?CreatePhoneRequest
    {
        return $this->mobilePhone;
    }

    /**
     * Sets Mobile Phone.
     *
     * @maps mobile_phone
     */
    public function setMobilePhone(?CreatePhoneRequest $mobilePhone): void
    {
        $this->mobilePhone = $mobilePhone;
    }

    /**
     * Converts the CreatePhonesRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePhonesRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePhonesRequest',
            ['homePhone' => $this->homePhone, 'mobilePhone' => $this->mobilePhone]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->homePhone)) {
            $json['home_phone']   = $this->homePhone;
        }
        if (isset($this->mobilePhone)) {
            $json['mobile_phone'] = $this->mobilePhone;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
