<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

class CreateCardPaymentContactlessPOIRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $systemName;

    /**
     * @var string
     */
    private $model;

    /**
     * @var string
     */
    private $provider;

    /**
     * @var string
     */
    private $serialNumber;

    /**
     * @var string
     */
    private $versionNumber;

    /**
     * @param string $systemName
     * @param string $model
     * @param string $provider
     * @param string $serialNumber
     * @param string $versionNumber
     */
    public function __construct(
        string $systemName,
        string $model,
        string $provider,
        string $serialNumber,
        string $versionNumber
    ) {
        $this->systemName = $systemName;
        $this->model = $model;
        $this->provider = $provider;
        $this->serialNumber = $serialNumber;
        $this->versionNumber = $versionNumber;
    }

    /**
     * Returns System Name.
     * system name
     */
    public function getSystemName(): string
    {
        return $this->systemName;
    }

    /**
     * Sets System Name.
     * system name
     *
     * @required
     * @maps system_name
     */
    public function setSystemName(string $systemName): void
    {
        $this->systemName = $systemName;
    }

    /**
     * Returns Model.
     * model
     */
    public function getModel(): string
    {
        return $this->model;
    }

    /**
     * Sets Model.
     * model
     *
     * @required
     * @maps model
     */
    public function setModel(string $model): void
    {
        $this->model = $model;
    }

    /**
     * Returns Provider.
     * provider
     */
    public function getProvider(): string
    {
        return $this->provider;
    }

    /**
     * Sets Provider.
     * provider
     *
     * @required
     * @maps provider
     */
    public function setProvider(string $provider): void
    {
        $this->provider = $provider;
    }

    /**
     * Returns Serial Number.
     * serial number
     */
    public function getSerialNumber(): string
    {
        return $this->serialNumber;
    }

    /**
     * Sets Serial Number.
     * serial number
     *
     * @required
     * @maps serial_number
     */
    public function setSerialNumber(string $serialNumber): void
    {
        $this->serialNumber = $serialNumber;
    }

    /**
     * Returns Version Number.
     * version number
     */
    public function getVersionNumber(): string
    {
        return $this->versionNumber;
    }

    /**
     * Sets Version Number.
     * version number
     *
     * @required
     * @maps version_number
     */
    public function setVersionNumber(string $versionNumber): void
    {
        $this->versionNumber = $versionNumber;
    }

    /**
     * Converts the CreateCardPaymentContactlessPOIRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateCardPaymentContactlessPOIRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateCardPaymentContactlessPOIRequest',
            [
                'systemName' => $this->systemName,
                'model' => $this->model,
                'provider' => $this->provider,
                'serialNumber' => $this->serialNumber,
                'versionNumber' => $this->versionNumber
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['system_name']    = $this->systemName;
        $json['model']          = $this->model;
        $json['provider']       = $this->provider;
        $json['serial_number']  = $this->serialNumber;
        $json['version_number'] = $this->versionNumber;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
