<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Request for creating an anticipation
 */
class CreateAnticipationRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $timeframe;

    /**
     * @var \DateTime
     */
    private $paymentDate;

    /**
     * @param int $amount
     * @param string $timeframe
     * @param \DateTime $paymentDate
     */
    public function __construct(int $amount, string $timeframe, \DateTime $paymentDate)
    {
        $this->amount = $amount;
        $this->timeframe = $timeframe;
        $this->paymentDate = $paymentDate;
    }

    /**
     * Returns Amount.
     * Amount requested for the anticipation
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Amount requested for the anticipation
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Timeframe.
     * Timeframe
     */
    public function getTimeframe(): string
    {
        return $this->timeframe;
    }

    /**
     * Sets Timeframe.
     * Timeframe
     *
     * @required
     * @maps timeframe
     */
    public function setTimeframe(string $timeframe): void
    {
        $this->timeframe = $timeframe;
    }

    /**
     * Returns Payment Date.
     * Payment date
     */
    public function getPaymentDate(): \DateTime
    {
        return $this->paymentDate;
    }

    /**
     * Sets Payment Date.
     * Payment date
     *
     * @required
     * @maps payment_date
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaymentDate(\DateTime $paymentDate): void
    {
        $this->paymentDate = $paymentDate;
    }

    /**
     * Converts the CreateAnticipationRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateAnticipationRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateAnticipationRequest',
            ['amount' => $this->amount, 'timeframe' => $this->timeframe, 'paymentDate' => $this->paymentDate]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']       = $this->amount;
        $json['timeframe']    = $this->timeframe;
        $json['payment_date'] = DateTimeHelper::toRfc3339DateTime($this->paymentDate);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
