<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Request for creating a Setup for a subscription. The setup is an order that will be created at the
 * subscription creation.
 */
class CreateSetupRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $description;

    /**
     * @var CreatePaymentRequest
     */
    private $payment;

    /**
     * @param int $amount
     * @param string $description
     * @param CreatePaymentRequest $payment
     */
    public function __construct(int $amount, string $description, CreatePaymentRequest $payment)
    {
        $this->amount = $amount;
        $this->description = $description;
        $this->payment = $payment;
    }

    /**
     * Returns Amount.
     * Setup amount
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Setup amount
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     * Description
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Payment.
     * Payment data
     */
    public function getPayment(): CreatePaymentRequest
    {
        return $this->payment;
    }

    /**
     * Sets Payment.
     * Payment data
     *
     * @required
     * @maps payment
     */
    public function setPayment(CreatePaymentRequest $payment): void
    {
        $this->payment = $payment;
    }

    /**
     * Converts the CreateSetupRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreateSetupRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateSetupRequest',
            ['amount' => $this->amount, 'description' => $this->description, 'payment' => $this->payment]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']      = $this->amount;
        $json['description'] = $this->description;
        $json['payment']     = $this->payment;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
