<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

class GetAutomaticAnticipationResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $enabled = [];

    /**
     * @var array
     */
    private $type = [];

    /**
     * @var array
     */
    private $volumePercentage = [];

    /**
     * @var array
     */
    private $delay = [];

    /**
     * @var array
     */
    private $days = [];

    /**
     * Returns Enabled.
     */
    public function getEnabled(): ?bool
    {
        if (count($this->enabled) == 0) {
            return null;
        }
        return $this->enabled['value'];
    }

    /**
     * Sets Enabled.
     *
     * @maps enabled
     */
    public function setEnabled(?bool $enabled): void
    {
        $this->enabled['value'] = $enabled;
    }

    /**
     * Unsets Enabled.
     */
    public function unsetEnabled(): void
    {
        $this->enabled = [];
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        if (count($this->type) == 0) {
            return null;
        }
        return $this->type['value'];
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type['value'] = $type;
    }

    /**
     * Unsets Type.
     */
    public function unsetType(): void
    {
        $this->type = [];
    }

    /**
     * Returns Volume Percentage.
     */
    public function getVolumePercentage(): ?int
    {
        if (count($this->volumePercentage) == 0) {
            return null;
        }
        return $this->volumePercentage['value'];
    }

    /**
     * Sets Volume Percentage.
     *
     * @maps volume_percentage
     */
    public function setVolumePercentage(?int $volumePercentage): void
    {
        $this->volumePercentage['value'] = $volumePercentage;
    }

    /**
     * Unsets Volume Percentage.
     */
    public function unsetVolumePercentage(): void
    {
        $this->volumePercentage = [];
    }

    /**
     * Returns Delay.
     */
    public function getDelay(): ?int
    {
        if (count($this->delay) == 0) {
            return null;
        }
        return $this->delay['value'];
    }

    /**
     * Sets Delay.
     *
     * @maps delay
     */
    public function setDelay(?int $delay): void
    {
        $this->delay['value'] = $delay;
    }

    /**
     * Unsets Delay.
     */
    public function unsetDelay(): void
    {
        $this->delay = [];
    }

    /**
     * Returns Days.
     *
     * @return int[]|null
     */
    public function getDays(): ?array
    {
        if (count($this->days) == 0) {
            return null;
        }
        return $this->days['value'];
    }

    /**
     * Sets Days.
     *
     * @maps days
     *
     * @param int[]|null $days
     */
    public function setDays(?array $days): void
    {
        $this->days['value'] = $days;
    }

    /**
     * Unsets Days.
     */
    public function unsetDays(): void
    {
        $this->days = [];
    }

    /**
     * Converts the GetAutomaticAnticipationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetAutomaticAnticipationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetAutomaticAnticipationResponse',
            [
                'enabled' => $this->getEnabled(),
                'type' => $this->getType(),
                'volumePercentage' => $this->getVolumePercentage(),
                'delay' => $this->getDelay(),
                'days' => $this->getDays()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->enabled)) {
            $json['enabled']           = $this->enabled['value'];
        }
        if (!empty($this->type)) {
            $json['type']              = $this->type['value'];
        }
        if (!empty($this->volumePercentage)) {
            $json['volume_percentage'] = $this->volumePercentage['value'];
        }
        if (!empty($this->delay)) {
            $json['delay']             = $this->delay['value'];
        }
        if (!empty($this->days)) {
            $json['days']              = $this->days['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
