<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting a boleto transaction
 *
 * @discriminator transaction_type
 * @discriminatorType boleto
 */
class GetBoletoTransactionResponse extends GetTransactionResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $barcode = [];

    /**
     * @var array
     */
    private $nossoNumero = [];

    /**
     * @var array
     */
    private $bank = [];

    /**
     * @var array
     */
    private $documentNumber = [];

    /**
     * @var array
     */
    private $instructions = [];

    /**
     * @var array
     */
    private $billingAddress = [];

    /**
     * @var array
     */
    private $dueAt = [];

    /**
     * @var array
     */
    private $qrCode = [];

    /**
     * @var array
     */
    private $line = [];

    /**
     * @var array
     */
    private $pdfPassword = [];

    /**
     * @var array
     */
    private $pdf = [];

    /**
     * @var array
     */
    private $paidAt = [];

    /**
     * @var array
     */
    private $paidAmount = [];

    /**
     * @var array
     */
    private $type = [];

    /**
     * @var array
     */
    private $creditAt = [];

    /**
     * @var array
     */
    private $statementDescriptor = [];

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Barcode.
     */
    public function getBarcode(): ?string
    {
        if (count($this->barcode) == 0) {
            return null;
        }
        return $this->barcode['value'];
    }

    /**
     * Sets Barcode.
     *
     * @maps barcode
     */
    public function setBarcode(?string $barcode): void
    {
        $this->barcode['value'] = $barcode;
    }

    /**
     * Unsets Barcode.
     */
    public function unsetBarcode(): void
    {
        $this->barcode = [];
    }

    /**
     * Returns Nosso Numero.
     */
    public function getNossoNumero(): ?string
    {
        if (count($this->nossoNumero) == 0) {
            return null;
        }
        return $this->nossoNumero['value'];
    }

    /**
     * Sets Nosso Numero.
     *
     * @maps nosso_numero
     */
    public function setNossoNumero(?string $nossoNumero): void
    {
        $this->nossoNumero['value'] = $nossoNumero;
    }

    /**
     * Unsets Nosso Numero.
     */
    public function unsetNossoNumero(): void
    {
        $this->nossoNumero = [];
    }

    /**
     * Returns Bank.
     */
    public function getBank(): ?string
    {
        if (count($this->bank) == 0) {
            return null;
        }
        return $this->bank['value'];
    }

    /**
     * Sets Bank.
     *
     * @maps bank
     */
    public function setBank(?string $bank): void
    {
        $this->bank['value'] = $bank;
    }

    /**
     * Unsets Bank.
     */
    public function unsetBank(): void
    {
        $this->bank = [];
    }

    /**
     * Returns Document Number.
     */
    public function getDocumentNumber(): ?string
    {
        if (count($this->documentNumber) == 0) {
            return null;
        }
        return $this->documentNumber['value'];
    }

    /**
     * Sets Document Number.
     *
     * @maps document_number
     */
    public function setDocumentNumber(?string $documentNumber): void
    {
        $this->documentNumber['value'] = $documentNumber;
    }

    /**
     * Unsets Document Number.
     */
    public function unsetDocumentNumber(): void
    {
        $this->documentNumber = [];
    }

    /**
     * Returns Instructions.
     */
    public function getInstructions(): ?string
    {
        if (count($this->instructions) == 0) {
            return null;
        }
        return $this->instructions['value'];
    }

    /**
     * Sets Instructions.
     *
     * @maps instructions
     */
    public function setInstructions(?string $instructions): void
    {
        $this->instructions['value'] = $instructions;
    }

    /**
     * Unsets Instructions.
     */
    public function unsetInstructions(): void
    {
        $this->instructions = [];
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?GetBillingAddressResponse
    {
        if (count($this->billingAddress) == 0) {
            return null;
        }
        return $this->billingAddress['value'];
    }

    /**
     * Sets Billing Address.
     *
     * @maps billing_address
     */
    public function setBillingAddress(?GetBillingAddressResponse $billingAddress): void
    {
        $this->billingAddress['value'] = $billingAddress;
    }

    /**
     * Unsets Billing Address.
     */
    public function unsetBillingAddress(): void
    {
        $this->billingAddress = [];
    }

    /**
     * Returns Due At.
     */
    public function getDueAt(): ?\DateTime
    {
        if (count($this->dueAt) == 0) {
            return null;
        }
        return $this->dueAt['value'];
    }

    /**
     * Sets Due At.
     *
     * @maps due_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDueAt(?\DateTime $dueAt): void
    {
        $this->dueAt['value'] = $dueAt;
    }

    /**
     * Unsets Due At.
     */
    public function unsetDueAt(): void
    {
        $this->dueAt = [];
    }

    /**
     * Returns Qr Code.
     */
    public function getQrCode(): ?string
    {
        if (count($this->qrCode) == 0) {
            return null;
        }
        return $this->qrCode['value'];
    }

    /**
     * Sets Qr Code.
     *
     * @maps qr_code
     */
    public function setQrCode(?string $qrCode): void
    {
        $this->qrCode['value'] = $qrCode;
    }

    /**
     * Unsets Qr Code.
     */
    public function unsetQrCode(): void
    {
        $this->qrCode = [];
    }

    /**
     * Returns Line.
     */
    public function getLine(): ?string
    {
        if (count($this->line) == 0) {
            return null;
        }
        return $this->line['value'];
    }

    /**
     * Sets Line.
     *
     * @maps line
     */
    public function setLine(?string $line): void
    {
        $this->line['value'] = $line;
    }

    /**
     * Unsets Line.
     */
    public function unsetLine(): void
    {
        $this->line = [];
    }

    /**
     * Returns Pdf Password.
     */
    public function getPdfPassword(): ?string
    {
        if (count($this->pdfPassword) == 0) {
            return null;
        }
        return $this->pdfPassword['value'];
    }

    /**
     * Sets Pdf Password.
     *
     * @maps pdf_password
     */
    public function setPdfPassword(?string $pdfPassword): void
    {
        $this->pdfPassword['value'] = $pdfPassword;
    }

    /**
     * Unsets Pdf Password.
     */
    public function unsetPdfPassword(): void
    {
        $this->pdfPassword = [];
    }

    /**
     * Returns Pdf.
     */
    public function getPdf(): ?string
    {
        if (count($this->pdf) == 0) {
            return null;
        }
        return $this->pdf['value'];
    }

    /**
     * Sets Pdf.
     *
     * @maps pdf
     */
    public function setPdf(?string $pdf): void
    {
        $this->pdf['value'] = $pdf;
    }

    /**
     * Unsets Pdf.
     */
    public function unsetPdf(): void
    {
        $this->pdf = [];
    }

    /**
     * Returns Paid At.
     */
    public function getPaidAt(): ?\DateTime
    {
        if (count($this->paidAt) == 0) {
            return null;
        }
        return $this->paidAt['value'];
    }

    /**
     * Sets Paid At.
     *
     * @maps paid_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaidAt(?\DateTime $paidAt): void
    {
        $this->paidAt['value'] = $paidAt;
    }

    /**
     * Unsets Paid At.
     */
    public function unsetPaidAt(): void
    {
        $this->paidAt = [];
    }

    /**
     * Returns Paid Amount.
     */
    public function getPaidAmount(): ?string
    {
        if (count($this->paidAmount) == 0) {
            return null;
        }
        return $this->paidAmount['value'];
    }

    /**
     * Sets Paid Amount.
     *
     * @maps paid_amount
     */
    public function setPaidAmount(?string $paidAmount): void
    {
        $this->paidAmount['value'] = $paidAmount;
    }

    /**
     * Unsets Paid Amount.
     */
    public function unsetPaidAmount(): void
    {
        $this->paidAmount = [];
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        if (count($this->type) == 0) {
            return null;
        }
        return $this->type['value'];
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type['value'] = $type;
    }

    /**
     * Unsets Type.
     */
    public function unsetType(): void
    {
        $this->type = [];
    }

    /**
     * Returns Credit At.
     */
    public function getCreditAt(): ?\DateTime
    {
        if (count($this->creditAt) == 0) {
            return null;
        }
        return $this->creditAt['value'];
    }

    /**
     * Sets Credit At.
     *
     * @maps credit_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreditAt(?\DateTime $creditAt): void
    {
        $this->creditAt['value'] = $creditAt;
    }

    /**
     * Unsets Credit At.
     */
    public function unsetCreditAt(): void
    {
        $this->creditAt = [];
    }

    /**
     * Returns Statement Descriptor.
     * Soft Descriptor
     */
    public function getStatementDescriptor(): ?string
    {
        if (count($this->statementDescriptor) == 0) {
            return null;
        }
        return $this->statementDescriptor['value'];
    }

    /**
     * Sets Statement Descriptor.
     * Soft Descriptor
     *
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(?string $statementDescriptor): void
    {
        $this->statementDescriptor['value'] = $statementDescriptor;
    }

    /**
     * Unsets Statement Descriptor.
     * Soft Descriptor
     */
    public function unsetStatementDescriptor(): void
    {
        $this->statementDescriptor = [];
    }

    /**
     * Converts the GetBoletoTransactionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetBoletoTransactionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetBoletoTransactionResponse',
            [
                'url' => $this->getUrl(),
                'barcode' => $this->getBarcode(),
                'nossoNumero' => $this->getNossoNumero(),
                'bank' => $this->getBank(),
                'documentNumber' => $this->getDocumentNumber(),
                'instructions' => $this->getInstructions(),
                'billingAddress' => $this->getBillingAddress(),
                'dueAt' => $this->getDueAt(),
                'qrCode' => $this->getQrCode(),
                'line' => $this->getLine(),
                'pdfPassword' => $this->getPdfPassword(),
                'pdf' => $this->getPdf(),
                'paidAt' => $this->getPaidAt(),
                'paidAmount' => $this->getPaidAmount(),
                'type' => $this->getType(),
                'creditAt' => $this->getCreditAt(),
                'statementDescriptor' => $this->getStatementDescriptor()
            ],
            parent::__toString()
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->url)) {
            $json['url']                  = $this->url['value'];
        }
        if (!empty($this->barcode)) {
            $json['barcode']              = $this->barcode['value'];
        }
        if (!empty($this->nossoNumero)) {
            $json['nosso_numero']         = $this->nossoNumero['value'];
        }
        if (!empty($this->bank)) {
            $json['bank']                 = $this->bank['value'];
        }
        if (!empty($this->documentNumber)) {
            $json['document_number']      = $this->documentNumber['value'];
        }
        if (!empty($this->instructions)) {
            $json['instructions']         = $this->instructions['value'];
        }
        if (!empty($this->billingAddress)) {
            $json['billing_address']      = $this->billingAddress['value'];
        }
        if (!empty($this->dueAt)) {
            $json['due_at']               = DateTimeHelper::toRfc3339DateTime($this->dueAt['value']);
        }
        if (!empty($this->qrCode)) {
            $json['qr_code']              = $this->qrCode['value'];
        }
        if (!empty($this->line)) {
            $json['line']                 = $this->line['value'];
        }
        if (!empty($this->pdfPassword)) {
            $json['pdf_password']         = $this->pdfPassword['value'];
        }
        if (!empty($this->pdf)) {
            $json['pdf']                  = $this->pdf['value'];
        }
        if (!empty($this->paidAt)) {
            $json['paid_at']              = DateTimeHelper::toRfc3339DateTime($this->paidAt['value']);
        }
        if (!empty($this->paidAmount)) {
            $json['paid_amount']          = $this->paidAmount['value'];
        }
        if (!empty($this->type)) {
            $json['type']                 = $this->type['value'];
        }
        if (!empty($this->creditAt)) {
            $json['credit_at']            = DateTimeHelper::toRfc3339DateTime($this->creditAt['value']);
        }
        if (!empty($this->statementDescriptor)) {
            $json['statement_descriptor'] = $this->statementDescriptor['value'];
        }
        $json = array_merge($json, parent::jsonSerialize(true));
        $json['transaction_type'] = $this->getTransactionType() ?? 'boleto';

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
