<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting a bank transfer transaction
 *
 * @discriminator transaction_type
 * @discriminatorType bank_transfer
 */
class GetBankTransferTransactionResponse extends GetTransactionResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string|null
     */
    private $bankTid;

    /**
     * @var string|null
     */
    private $bank;

    /**
     * @var \DateTime|null
     */
    private $paidAt;

    /**
     * @var int|null
     */
    private $paidAmount;

    /**
     * Returns Url.
     * Payment url
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * Payment url
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Bank Tid.
     * Transaction identifier for the bank
     */
    public function getBankTid(): ?string
    {
        return $this->bankTid;
    }

    /**
     * Sets Bank Tid.
     * Transaction identifier for the bank
     *
     * @maps bank_tid
     */
    public function setBankTid(?string $bankTid): void
    {
        $this->bankTid = $bankTid;
    }

    /**
     * Returns Bank.
     * Bank
     */
    public function getBank(): ?string
    {
        return $this->bank;
    }

    /**
     * Sets Bank.
     * Bank
     *
     * @maps bank
     */
    public function setBank(?string $bank): void
    {
        $this->bank = $bank;
    }

    /**
     * Returns Paid At.
     * Payment date
     */
    public function getPaidAt(): ?\DateTime
    {
        return $this->paidAt;
    }

    /**
     * Sets Paid At.
     * Payment date
     *
     * @maps paid_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaidAt(?\DateTime $paidAt): void
    {
        $this->paidAt = $paidAt;
    }

    /**
     * Returns Paid Amount.
     * Paid amount
     */
    public function getPaidAmount(): ?int
    {
        return $this->paidAmount;
    }

    /**
     * Sets Paid Amount.
     * Paid amount
     *
     * @maps paid_amount
     */
    public function setPaidAmount(?int $paidAmount): void
    {
        $this->paidAmount = $paidAmount;
    }

    /**
     * Converts the GetBankTransferTransactionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetBankTransferTransactionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetBankTransferTransactionResponse',
            [
                'url' => $this->url,
                'bankTid' => $this->bankTid,
                'bank' => $this->bank,
                'paidAt' => $this->paidAt,
                'paidAmount' => $this->paidAmount
            ],
            parent::__toString()
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->url)) {
            $json['url']         = $this->url;
        }
        if (isset($this->bankTid)) {
            $json['bank_tid']    = $this->bankTid;
        }
        if (isset($this->bank)) {
            $json['bank']        = $this->bank;
        }
        if (isset($this->paidAt)) {
            $json['paid_at']     = DateTimeHelper::toRfc3339DateTime($this->paidAt);
        }
        if (isset($this->paidAmount)) {
            $json['paid_amount'] = $this->paidAmount;
        }
        $json = array_merge($json, parent::jsonSerialize(true));
        $json['transaction_type'] = $this->getTransactionType() ?? 'bank_transfer';

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
