<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Response object for getting a billing address
 */
class GetBillingAddressResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $street = [];

    /**
     * @var array
     */
    private $number = [];

    /**
     * @var array
     */
    private $zipCode = [];

    /**
     * @var array
     */
    private $neighborhood = [];

    /**
     * @var array
     */
    private $city = [];

    /**
     * @var array
     */
    private $state = [];

    /**
     * @var array
     */
    private $country = [];

    /**
     * @var array
     */
    private $complement = [];

    /**
     * @var array
     */
    private $line1 = [];

    /**
     * @var array
     */
    private $line2 = [];

    /**
     * Returns Street.
     */
    public function getStreet(): ?string
    {
        if (count($this->street) == 0) {
            return null;
        }
        return $this->street['value'];
    }

    /**
     * Sets Street.
     *
     * @maps street
     */
    public function setStreet(?string $street): void
    {
        $this->street['value'] = $street;
    }

    /**
     * Unsets Street.
     */
    public function unsetStreet(): void
    {
        $this->street = [];
    }

    /**
     * Returns Number.
     */
    public function getNumber(): ?string
    {
        if (count($this->number) == 0) {
            return null;
        }
        return $this->number['value'];
    }

    /**
     * Sets Number.
     *
     * @maps number
     */
    public function setNumber(?string $number): void
    {
        $this->number['value'] = $number;
    }

    /**
     * Unsets Number.
     */
    public function unsetNumber(): void
    {
        $this->number = [];
    }

    /**
     * Returns Zip Code.
     */
    public function getZipCode(): ?string
    {
        if (count($this->zipCode) == 0) {
            return null;
        }
        return $this->zipCode['value'];
    }

    /**
     * Sets Zip Code.
     *
     * @maps zip_code
     */
    public function setZipCode(?string $zipCode): void
    {
        $this->zipCode['value'] = $zipCode;
    }

    /**
     * Unsets Zip Code.
     */
    public function unsetZipCode(): void
    {
        $this->zipCode = [];
    }

    /**
     * Returns Neighborhood.
     */
    public function getNeighborhood(): ?string
    {
        if (count($this->neighborhood) == 0) {
            return null;
        }
        return $this->neighborhood['value'];
    }

    /**
     * Sets Neighborhood.
     *
     * @maps neighborhood
     */
    public function setNeighborhood(?string $neighborhood): void
    {
        $this->neighborhood['value'] = $neighborhood;
    }

    /**
     * Unsets Neighborhood.
     */
    public function unsetNeighborhood(): void
    {
        $this->neighborhood = [];
    }

    /**
     * Returns City.
     */
    public function getCity(): ?string
    {
        if (count($this->city) == 0) {
            return null;
        }
        return $this->city['value'];
    }

    /**
     * Sets City.
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city['value'] = $city;
    }

    /**
     * Unsets City.
     */
    public function unsetCity(): void
    {
        $this->city = [];
    }

    /**
     * Returns State.
     */
    public function getState(): ?string
    {
        if (count($this->state) == 0) {
            return null;
        }
        return $this->state['value'];
    }

    /**
     * Sets State.
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state['value'] = $state;
    }

    /**
     * Unsets State.
     */
    public function unsetState(): void
    {
        $this->state = [];
    }

    /**
     * Returns Country.
     */
    public function getCountry(): ?string
    {
        if (count($this->country) == 0) {
            return null;
        }
        return $this->country['value'];
    }

    /**
     * Sets Country.
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country['value'] = $country;
    }

    /**
     * Unsets Country.
     */
    public function unsetCountry(): void
    {
        $this->country = [];
    }

    /**
     * Returns Complement.
     */
    public function getComplement(): ?string
    {
        if (count($this->complement) == 0) {
            return null;
        }
        return $this->complement['value'];
    }

    /**
     * Sets Complement.
     *
     * @maps complement
     */
    public function setComplement(?string $complement): void
    {
        $this->complement['value'] = $complement;
    }

    /**
     * Unsets Complement.
     */
    public function unsetComplement(): void
    {
        $this->complement = [];
    }

    /**
     * Returns Line 1.
     * Line 1 for address
     */
    public function getLine1(): ?string
    {
        if (count($this->line1) == 0) {
            return null;
        }
        return $this->line1['value'];
    }

    /**
     * Sets Line 1.
     * Line 1 for address
     *
     * @maps line_1
     */
    public function setLine1(?string $line1): void
    {
        $this->line1['value'] = $line1;
    }

    /**
     * Unsets Line 1.
     * Line 1 for address
     */
    public function unsetLine1(): void
    {
        $this->line1 = [];
    }

    /**
     * Returns Line 2.
     * Line 2 for address
     */
    public function getLine2(): ?string
    {
        if (count($this->line2) == 0) {
            return null;
        }
        return $this->line2['value'];
    }

    /**
     * Sets Line 2.
     * Line 2 for address
     *
     * @maps line_2
     */
    public function setLine2(?string $line2): void
    {
        $this->line2['value'] = $line2;
    }

    /**
     * Unsets Line 2.
     * Line 2 for address
     */
    public function unsetLine2(): void
    {
        $this->line2 = [];
    }

    /**
     * Converts the GetBillingAddressResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetBillingAddressResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetBillingAddressResponse',
            [
                'street' => $this->getStreet(),
                'number' => $this->getNumber(),
                'zipCode' => $this->getZipCode(),
                'neighborhood' => $this->getNeighborhood(),
                'city' => $this->getCity(),
                'state' => $this->getState(),
                'country' => $this->getCountry(),
                'complement' => $this->getComplement(),
                'line1' => $this->getLine1(),
                'line2' => $this->getLine2()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->street)) {
            $json['street']       = $this->street['value'];
        }
        if (!empty($this->number)) {
            $json['number']       = $this->number['value'];
        }
        if (!empty($this->zipCode)) {
            $json['zip_code']     = $this->zipCode['value'];
        }
        if (!empty($this->neighborhood)) {
            $json['neighborhood'] = $this->neighborhood['value'];
        }
        if (!empty($this->city)) {
            $json['city']         = $this->city['value'];
        }
        if (!empty($this->state)) {
            $json['state']        = $this->state['value'];
        }
        if (!empty($this->country)) {
            $json['country']      = $this->country['value'];
        }
        if (!empty($this->complement)) {
            $json['complement']   = $this->complement['value'];
        }
        if (!empty($this->line1)) {
            $json['line_1']       = $this->line1['value'];
        }
        if (!empty($this->line2)) {
            $json['line_2']       = $this->line2['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
