<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Generic response object for getting a MovementObjectFeeCollection.
 *
 * @discriminator object
 * @discriminatorType feeCollection
 */
class GetMovementObjectFeeCollectionResponse extends GetMovementObjectBaseResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $description = [];

    /**
     * @var array
     */
    private $paymentDate = [];

    /**
     * @var array
     */
    private $recipientId = [];

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        if (count($this->description) == 0) {
            return null;
        }
        return $this->description['value'];
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description['value'] = $description;
    }

    /**
     * Unsets Description.
     */
    public function unsetDescription(): void
    {
        $this->description = [];
    }

    /**
     * Returns Payment Date.
     */
    public function getPaymentDate(): ?string
    {
        if (count($this->paymentDate) == 0) {
            return null;
        }
        return $this->paymentDate['value'];
    }

    /**
     * Sets Payment Date.
     *
     * @maps payment_date
     */
    public function setPaymentDate(?string $paymentDate): void
    {
        $this->paymentDate['value'] = $paymentDate;
    }

    /**
     * Unsets Payment Date.
     */
    public function unsetPaymentDate(): void
    {
        $this->paymentDate = [];
    }

    /**
     * Returns Recipient Id.
     */
    public function getRecipientId(): ?string
    {
        if (count($this->recipientId) == 0) {
            return null;
        }
        return $this->recipientId['value'];
    }

    /**
     * Sets Recipient Id.
     *
     * @maps recipient_id
     */
    public function setRecipientId(?string $recipientId): void
    {
        $this->recipientId['value'] = $recipientId;
    }

    /**
     * Unsets Recipient Id.
     */
    public function unsetRecipientId(): void
    {
        $this->recipientId = [];
    }

    /**
     * Converts the GetMovementObjectFeeCollectionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetMovementObjectFeeCollectionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetMovementObjectFeeCollectionResponse',
            [
                'description' => $this->getDescription(),
                'paymentDate' => $this->getPaymentDate(),
                'recipientId' => $this->getRecipientId()
            ],
            parent::__toString()
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->description)) {
            $json['description']  = $this->description['value'];
        }
        if (!empty($this->paymentDate)) {
            $json['payment_date'] = $this->paymentDate['value'];
        }
        if (!empty($this->recipientId)) {
            $json['recipient_id'] = $this->recipientId['value'];
        }
        $json = array_merge($json, parent::jsonSerialize(true));
        $json['object'] = $this->getObject() ?? 'feeCollection';

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
