<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Payer's bank details.
 */
class GetPixBankAccountResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $bankName = [];

    /**
     * @var array
     */
    private $ispb = [];

    /**
     * @var array
     */
    private $branchCode = [];

    /**
     * @var array
     */
    private $accountNumber = [];

    /**
     * Returns Bank Name.
     */
    public function getBankName(): ?string
    {
        if (count($this->bankName) == 0) {
            return null;
        }
        return $this->bankName['value'];
    }

    /**
     * Sets Bank Name.
     *
     * @maps bank_name
     */
    public function setBankName(?string $bankName): void
    {
        $this->bankName['value'] = $bankName;
    }

    /**
     * Unsets Bank Name.
     */
    public function unsetBankName(): void
    {
        $this->bankName = [];
    }

    /**
     * Returns Ispb.
     */
    public function getIspb(): ?string
    {
        if (count($this->ispb) == 0) {
            return null;
        }
        return $this->ispb['value'];
    }

    /**
     * Sets Ispb.
     *
     * @maps ispb
     */
    public function setIspb(?string $ispb): void
    {
        $this->ispb['value'] = $ispb;
    }

    /**
     * Unsets Ispb.
     */
    public function unsetIspb(): void
    {
        $this->ispb = [];
    }

    /**
     * Returns Branch Code.
     */
    public function getBranchCode(): ?string
    {
        if (count($this->branchCode) == 0) {
            return null;
        }
        return $this->branchCode['value'];
    }

    /**
     * Sets Branch Code.
     *
     * @maps branch_code
     */
    public function setBranchCode(?string $branchCode): void
    {
        $this->branchCode['value'] = $branchCode;
    }

    /**
     * Unsets Branch Code.
     */
    public function unsetBranchCode(): void
    {
        $this->branchCode = [];
    }

    /**
     * Returns Account Number.
     */
    public function getAccountNumber(): ?string
    {
        if (count($this->accountNumber) == 0) {
            return null;
        }
        return $this->accountNumber['value'];
    }

    /**
     * Sets Account Number.
     *
     * @maps account_number
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber['value'] = $accountNumber;
    }

    /**
     * Unsets Account Number.
     */
    public function unsetAccountNumber(): void
    {
        $this->accountNumber = [];
    }

    /**
     * Converts the GetPixBankAccountResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetPixBankAccountResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetPixBankAccountResponse',
            [
                'bankName' => $this->getBankName(),
                'ispb' => $this->getIspb(),
                'branchCode' => $this->getBranchCode(),
                'accountNumber' => $this->getAccountNumber()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->bankName)) {
            $json['bank_name']      = $this->bankName['value'];
        }
        if (!empty($this->ispb)) {
            $json['ispb']           = $this->ispb['value'];
        }
        if (!empty($this->branchCode)) {
            $json['branch_code']    = $this->branchCode['value'];
        }
        if (!empty($this->accountNumber)) {
            $json['account_number'] = $this->accountNumber['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
