<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object when getting a pix transaction
 *
 * @discriminator transaction_type
 * @discriminatorType pix
 */
class GetPixTransactionResponse extends GetTransactionResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $qrCode = [];

    /**
     * @var array
     */
    private $qrCodeUrl = [];

    /**
     * @var array
     */
    private $expiresAt = [];

    /**
     * @var array
     */
    private $additionalInformation = [];

    /**
     * @var array
     */
    private $endToEndId = [];

    /**
     * @var array
     */
    private $payer = [];

    /**
     * @var array
     */
    private $pixProviderTid = [];

    /**
     * Returns Qr Code.
     */
    public function getQrCode(): ?string
    {
        if (count($this->qrCode) == 0) {
            return null;
        }
        return $this->qrCode['value'];
    }

    /**
     * Sets Qr Code.
     *
     * @maps qr_code
     */
    public function setQrCode(?string $qrCode): void
    {
        $this->qrCode['value'] = $qrCode;
    }

    /**
     * Unsets Qr Code.
     */
    public function unsetQrCode(): void
    {
        $this->qrCode = [];
    }

    /**
     * Returns Qr Code Url.
     */
    public function getQrCodeUrl(): ?string
    {
        if (count($this->qrCodeUrl) == 0) {
            return null;
        }
        return $this->qrCodeUrl['value'];
    }

    /**
     * Sets Qr Code Url.
     *
     * @maps qr_code_url
     */
    public function setQrCodeUrl(?string $qrCodeUrl): void
    {
        $this->qrCodeUrl['value'] = $qrCodeUrl;
    }

    /**
     * Unsets Qr Code Url.
     */
    public function unsetQrCodeUrl(): void
    {
        $this->qrCodeUrl = [];
    }

    /**
     * Returns Expires At.
     */
    public function getExpiresAt(): ?\DateTime
    {
        if (count($this->expiresAt) == 0) {
            return null;
        }
        return $this->expiresAt['value'];
    }

    /**
     * Sets Expires At.
     *
     * @maps expires_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpiresAt(?\DateTime $expiresAt): void
    {
        $this->expiresAt['value'] = $expiresAt;
    }

    /**
     * Unsets Expires At.
     */
    public function unsetExpiresAt(): void
    {
        $this->expiresAt = [];
    }

    /**
     * Returns Additional Information.
     *
     * @return PixAdditionalInformation[]|null
     */
    public function getAdditionalInformation(): ?array
    {
        if (count($this->additionalInformation) == 0) {
            return null;
        }
        return $this->additionalInformation['value'];
    }

    /**
     * Sets Additional Information.
     *
     * @maps additional_information
     *
     * @param PixAdditionalInformation[]|null $additionalInformation
     */
    public function setAdditionalInformation(?array $additionalInformation): void
    {
        $this->additionalInformation['value'] = $additionalInformation;
    }

    /**
     * Unsets Additional Information.
     */
    public function unsetAdditionalInformation(): void
    {
        $this->additionalInformation = [];
    }

    /**
     * Returns End to End Id.
     */
    public function getEndToEndId(): ?string
    {
        if (count($this->endToEndId) == 0) {
            return null;
        }
        return $this->endToEndId['value'];
    }

    /**
     * Sets End to End Id.
     *
     * @maps end_to_end_id
     */
    public function setEndToEndId(?string $endToEndId): void
    {
        $this->endToEndId['value'] = $endToEndId;
    }

    /**
     * Unsets End to End Id.
     */
    public function unsetEndToEndId(): void
    {
        $this->endToEndId = [];
    }

    /**
     * Returns Payer.
     */
    public function getPayer(): ?GetPixPayerResponse
    {
        if (count($this->payer) == 0) {
            return null;
        }
        return $this->payer['value'];
    }

    /**
     * Sets Payer.
     *
     * @maps payer
     */
    public function setPayer(?GetPixPayerResponse $payer): void
    {
        $this->payer['value'] = $payer;
    }

    /**
     * Unsets Payer.
     */
    public function unsetPayer(): void
    {
        $this->payer = [];
    }

    /**
     * Returns Pix Provider Tid.
     * Pix provider TID
     */
    public function getPixProviderTid(): ?string
    {
        if (count($this->pixProviderTid) == 0) {
            return null;
        }
        return $this->pixProviderTid['value'];
    }

    /**
     * Sets Pix Provider Tid.
     * Pix provider TID
     *
     * @maps pix_provider_tid
     */
    public function setPixProviderTid(?string $pixProviderTid): void
    {
        $this->pixProviderTid['value'] = $pixProviderTid;
    }

    /**
     * Unsets Pix Provider Tid.
     * Pix provider TID
     */
    public function unsetPixProviderTid(): void
    {
        $this->pixProviderTid = [];
    }

    /**
     * Converts the GetPixTransactionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetPixTransactionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetPixTransactionResponse',
            [
                'qrCode' => $this->getQrCode(),
                'qrCodeUrl' => $this->getQrCodeUrl(),
                'expiresAt' => $this->getExpiresAt(),
                'additionalInformation' => $this->getAdditionalInformation(),
                'endToEndId' => $this->getEndToEndId(),
                'payer' => $this->getPayer(),
                'pixProviderTid' => $this->getPixProviderTid()
            ],
            parent::__toString()
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->qrCode)) {
            $json['qr_code']                = $this->qrCode['value'];
        }
        if (!empty($this->qrCodeUrl)) {
            $json['qr_code_url']            = $this->qrCodeUrl['value'];
        }
        if (!empty($this->expiresAt)) {
            $json['expires_at']             = DateTimeHelper::toRfc3339DateTime($this->expiresAt['value']);
        }
        if (!empty($this->additionalInformation)) {
            $json['additional_information'] = $this->additionalInformation['value'];
        }
        if (!empty($this->endToEndId)) {
            $json['end_to_end_id']          = $this->endToEndId['value'];
        }
        if (!empty($this->payer)) {
            $json['payer']                  = $this->payer['value'];
        }
        if (!empty($this->pixProviderTid)) {
            $json['pix_provider_tid']       = $this->pixProviderTid['value'];
        }
        $json = array_merge($json, parent::jsonSerialize(true));
        $json['transaction_type'] = $this->getTransactionType() ?? 'pix';

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
