<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting an RetryTransactionInformation
 */
class GetRetryTransactionInformationResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $brandFailureReturnCode;

    /**
     * @var int|null
     */
    private $transactionLimit;

    /**
     * @var \DateTime|null
     */
    private $transactionDateLimit;

    /**
     * Returns Brand Failure Return Code.
     */
    public function getBrandFailureReturnCode(): ?string
    {
        return $this->brandFailureReturnCode;
    }

    /**
     * Sets Brand Failure Return Code.
     *
     * @maps brand_failure_return_code
     */
    public function setBrandFailureReturnCode(?string $brandFailureReturnCode): void
    {
        $this->brandFailureReturnCode = $brandFailureReturnCode;
    }

    /**
     * Returns Transaction Limit.
     */
    public function getTransactionLimit(): ?int
    {
        return $this->transactionLimit;
    }

    /**
     * Sets Transaction Limit.
     *
     * @maps transaction_limit
     */
    public function setTransactionLimit(?int $transactionLimit): void
    {
        $this->transactionLimit = $transactionLimit;
    }

    /**
     * Returns Transaction Date Limit.
     */
    public function getTransactionDateLimit(): ?\DateTime
    {
        return $this->transactionDateLimit;
    }

    /**
     * Sets Transaction Date Limit.
     *
     * @maps transaction_date_limit
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTransactionDateLimit(?\DateTime $transactionDateLimit): void
    {
        $this->transactionDateLimit = $transactionDateLimit;
    }

    /**
     * Converts the GetRetryTransactionInformationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetRetryTransactionInformationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetRetryTransactionInformationResponse',
            [
                'brandFailureReturnCode' => $this->brandFailureReturnCode,
                'transactionLimit' => $this->transactionLimit,
                'transactionDateLimit' => $this->transactionDateLimit
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['brand_failure_return_code'] = $this->brandFailureReturnCode;
        $json['transaction_limit']         = $this->transactionLimit;
        $json['transaction_date_limit']    = DateTimeHelper::toRfc3339DateTime($this->transactionDateLimit);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
