<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

class GetSubscriptionResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $id = [];

    /**
     * @var array
     */
    private $code = [];

    /**
     * @var array
     */
    private $startAt = [];

    /**
     * @var array
     */
    private $interval = [];

    /**
     * @var array
     */
    private $intervalCount = [];

    /**
     * @var array
     */
    private $billingType = [];

    /**
     * @var array
     */
    private $currentCycle = [];

    /**
     * @var array
     */
    private $paymentMethod = [];

    /**
     * @var array
     */
    private $currency = [];

    /**
     * @var array
     */
    private $installments = [];

    /**
     * @var array
     */
    private $status = [];

    /**
     * @var array
     */
    private $createdAt = [];

    /**
     * @var array
     */
    private $updatedAt = [];

    /**
     * @var array
     */
    private $customer = [];

    /**
     * @var array
     */
    private $card = [];

    /**
     * @var array
     */
    private $items = [];

    /**
     * @var array
     */
    private $statementDescriptor = [];

    /**
     * @var array
     */
    private $metadata = [];

    /**
     * @var array
     */
    private $setup = [];

    /**
     * @var array
     */
    private $gatewayAffiliationId = [];

    /**
     * @var array
     */
    private $nextBillingAt = [];

    /**
     * @var array
     */
    private $billingDay = [];

    /**
     * @var array
     */
    private $minimumPrice = [];

    /**
     * @var array
     */
    private $canceledAt = [];

    /**
     * @var array
     */
    private $discounts = [];

    /**
     * @var array
     */
    private $increments = [];

    /**
     * @var array
     */
    private $boletoDueDays = [];

    /**
     * @var array
     */
    private $split = [];

    /**
     * @var array
     */
    private $boleto = [];

    /**
     * @var array
     */
    private $manualBilling = [];

    /**
     * @var array
     */
    private $indirectAcceptor = [];

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        if (count($this->id) == 0) {
            return null;
        }
        return $this->id['value'];
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id['value'] = $id;
    }

    /**
     * Unsets Id.
     */
    public function unsetId(): void
    {
        $this->id = [];
    }

    /**
     * Returns Code.
     */
    public function getCode(): ?string
    {
        if (count($this->code) == 0) {
            return null;
        }
        return $this->code['value'];
    }

    /**
     * Sets Code.
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code['value'] = $code;
    }

    /**
     * Unsets Code.
     */
    public function unsetCode(): void
    {
        $this->code = [];
    }

    /**
     * Returns Start At.
     */
    public function getStartAt(): ?\DateTime
    {
        if (count($this->startAt) == 0) {
            return null;
        }
        return $this->startAt['value'];
    }

    /**
     * Sets Start At.
     *
     * @maps start_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStartAt(?\DateTime $startAt): void
    {
        $this->startAt['value'] = $startAt;
    }

    /**
     * Unsets Start At.
     */
    public function unsetStartAt(): void
    {
        $this->startAt = [];
    }

    /**
     * Returns Interval.
     */
    public function getInterval(): ?string
    {
        if (count($this->interval) == 0) {
            return null;
        }
        return $this->interval['value'];
    }

    /**
     * Sets Interval.
     *
     * @maps interval
     */
    public function setInterval(?string $interval): void
    {
        $this->interval['value'] = $interval;
    }

    /**
     * Unsets Interval.
     */
    public function unsetInterval(): void
    {
        $this->interval = [];
    }

    /**
     * Returns Interval Count.
     */
    public function getIntervalCount(): ?int
    {
        if (count($this->intervalCount) == 0) {
            return null;
        }
        return $this->intervalCount['value'];
    }

    /**
     * Sets Interval Count.
     *
     * @maps interval_count
     */
    public function setIntervalCount(?int $intervalCount): void
    {
        $this->intervalCount['value'] = $intervalCount;
    }

    /**
     * Unsets Interval Count.
     */
    public function unsetIntervalCount(): void
    {
        $this->intervalCount = [];
    }

    /**
     * Returns Billing Type.
     */
    public function getBillingType(): ?string
    {
        if (count($this->billingType) == 0) {
            return null;
        }
        return $this->billingType['value'];
    }

    /**
     * Sets Billing Type.
     *
     * @maps billing_type
     */
    public function setBillingType(?string $billingType): void
    {
        $this->billingType['value'] = $billingType;
    }

    /**
     * Unsets Billing Type.
     */
    public function unsetBillingType(): void
    {
        $this->billingType = [];
    }

    /**
     * Returns Current Cycle.
     */
    public function getCurrentCycle(): ?GetPeriodResponse
    {
        if (count($this->currentCycle) == 0) {
            return null;
        }
        return $this->currentCycle['value'];
    }

    /**
     * Sets Current Cycle.
     *
     * @maps current_cycle
     */
    public function setCurrentCycle(?GetPeriodResponse $currentCycle): void
    {
        $this->currentCycle['value'] = $currentCycle;
    }

    /**
     * Unsets Current Cycle.
     */
    public function unsetCurrentCycle(): void
    {
        $this->currentCycle = [];
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?string
    {
        if (count($this->paymentMethod) == 0) {
            return null;
        }
        return $this->paymentMethod['value'];
    }

    /**
     * Sets Payment Method.
     *
     * @maps payment_method
     */
    public function setPaymentMethod(?string $paymentMethod): void
    {
        $this->paymentMethod['value'] = $paymentMethod;
    }

    /**
     * Unsets Payment Method.
     */
    public function unsetPaymentMethod(): void
    {
        $this->paymentMethod = [];
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        if (count($this->currency) == 0) {
            return null;
        }
        return $this->currency['value'];
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency['value'] = $currency;
    }

    /**
     * Unsets Currency.
     */
    public function unsetCurrency(): void
    {
        $this->currency = [];
    }

    /**
     * Returns Installments.
     */
    public function getInstallments(): ?int
    {
        if (count($this->installments) == 0) {
            return null;
        }
        return $this->installments['value'];
    }

    /**
     * Sets Installments.
     *
     * @maps installments
     */
    public function setInstallments(?int $installments): void
    {
        $this->installments['value'] = $installments;
    }

    /**
     * Unsets Installments.
     */
    public function unsetInstallments(): void
    {
        $this->installments = [];
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        if (count($this->status) == 0) {
            return null;
        }
        return $this->status['value'];
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status['value'] = $status;
    }

    /**
     * Unsets Status.
     */
    public function unsetStatus(): void
    {
        $this->status = [];
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?\DateTime
    {
        if (count($this->createdAt) == 0) {
            return null;
        }
        return $this->createdAt['value'];
    }

    /**
     * Sets Created At.
     *
     * @maps created_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt['value'] = $createdAt;
    }

    /**
     * Unsets Created At.
     */
    public function unsetCreatedAt(): void
    {
        $this->createdAt = [];
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): ?\DateTime
    {
        if (count($this->updatedAt) == 0) {
            return null;
        }
        return $this->updatedAt['value'];
    }

    /**
     * Sets Updated At.
     *
     * @maps updated_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt['value'] = $updatedAt;
    }

    /**
     * Unsets Updated At.
     */
    public function unsetUpdatedAt(): void
    {
        $this->updatedAt = [];
    }

    /**
     * Returns Customer.
     */
    public function getCustomer(): ?GetCustomerResponse
    {
        if (count($this->customer) == 0) {
            return null;
        }
        return $this->customer['value'];
    }

    /**
     * Sets Customer.
     *
     * @maps customer
     */
    public function setCustomer(?GetCustomerResponse $customer): void
    {
        $this->customer['value'] = $customer;
    }

    /**
     * Unsets Customer.
     */
    public function unsetCustomer(): void
    {
        $this->customer = [];
    }

    /**
     * Returns Card.
     */
    public function getCard(): ?GetCardResponse
    {
        if (count($this->card) == 0) {
            return null;
        }
        return $this->card['value'];
    }

    /**
     * Sets Card.
     *
     * @maps card
     */
    public function setCard(?GetCardResponse $card): void
    {
        $this->card['value'] = $card;
    }

    /**
     * Unsets Card.
     */
    public function unsetCard(): void
    {
        $this->card = [];
    }

    /**
     * Returns Items.
     *
     * @return GetSubscriptionItemResponse[]|null
     */
    public function getItems(): ?array
    {
        if (count($this->items) == 0) {
            return null;
        }
        return $this->items['value'];
    }

    /**
     * Sets Items.
     *
     * @maps items
     *
     * @param GetSubscriptionItemResponse[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items['value'] = $items;
    }

    /**
     * Unsets Items.
     */
    public function unsetItems(): void
    {
        $this->items = [];
    }

    /**
     * Returns Statement Descriptor.
     */
    public function getStatementDescriptor(): ?string
    {
        if (count($this->statementDescriptor) == 0) {
            return null;
        }
        return $this->statementDescriptor['value'];
    }

    /**
     * Sets Statement Descriptor.
     *
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(?string $statementDescriptor): void
    {
        $this->statementDescriptor['value'] = $statementDescriptor;
    }

    /**
     * Unsets Statement Descriptor.
     */
    public function unsetStatementDescriptor(): void
    {
        $this->statementDescriptor = [];
    }

    /**
     * Returns Metadata.
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        if (count($this->metadata) == 0) {
            return null;
        }
        return $this->metadata['value'];
    }

    /**
     * Sets Metadata.
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata['value'] = $metadata;
    }

    /**
     * Unsets Metadata.
     */
    public function unsetMetadata(): void
    {
        $this->metadata = [];
    }

    /**
     * Returns Setup.
     */
    public function getSetup(): ?GetSetupResponse
    {
        if (count($this->setup) == 0) {
            return null;
        }
        return $this->setup['value'];
    }

    /**
     * Sets Setup.
     *
     * @maps setup
     */
    public function setSetup(?GetSetupResponse $setup): void
    {
        $this->setup['value'] = $setup;
    }

    /**
     * Unsets Setup.
     */
    public function unsetSetup(): void
    {
        $this->setup = [];
    }

    /**
     * Returns Gateway Affiliation Id.
     * Affiliation Code
     */
    public function getGatewayAffiliationId(): ?string
    {
        if (count($this->gatewayAffiliationId) == 0) {
            return null;
        }
        return $this->gatewayAffiliationId['value'];
    }

    /**
     * Sets Gateway Affiliation Id.
     * Affiliation Code
     *
     * @maps gateway_affiliation_id
     */
    public function setGatewayAffiliationId(?string $gatewayAffiliationId): void
    {
        $this->gatewayAffiliationId['value'] = $gatewayAffiliationId;
    }

    /**
     * Unsets Gateway Affiliation Id.
     * Affiliation Code
     */
    public function unsetGatewayAffiliationId(): void
    {
        $this->gatewayAffiliationId = [];
    }

    /**
     * Returns Next Billing At.
     */
    public function getNextBillingAt(): ?\DateTime
    {
        if (count($this->nextBillingAt) == 0) {
            return null;
        }
        return $this->nextBillingAt['value'];
    }

    /**
     * Sets Next Billing At.
     *
     * @maps next_billing_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setNextBillingAt(?\DateTime $nextBillingAt): void
    {
        $this->nextBillingAt['value'] = $nextBillingAt;
    }

    /**
     * Unsets Next Billing At.
     */
    public function unsetNextBillingAt(): void
    {
        $this->nextBillingAt = [];
    }

    /**
     * Returns Billing Day.
     */
    public function getBillingDay(): ?int
    {
        if (count($this->billingDay) == 0) {
            return null;
        }
        return $this->billingDay['value'];
    }

    /**
     * Sets Billing Day.
     *
     * @maps billing_day
     */
    public function setBillingDay(?int $billingDay): void
    {
        $this->billingDay['value'] = $billingDay;
    }

    /**
     * Unsets Billing Day.
     */
    public function unsetBillingDay(): void
    {
        $this->billingDay = [];
    }

    /**
     * Returns Minimum Price.
     */
    public function getMinimumPrice(): ?int
    {
        if (count($this->minimumPrice) == 0) {
            return null;
        }
        return $this->minimumPrice['value'];
    }

    /**
     * Sets Minimum Price.
     *
     * @maps minimum_price
     */
    public function setMinimumPrice(?int $minimumPrice): void
    {
        $this->minimumPrice['value'] = $minimumPrice;
    }

    /**
     * Unsets Minimum Price.
     */
    public function unsetMinimumPrice(): void
    {
        $this->minimumPrice = [];
    }

    /**
     * Returns Canceled At.
     */
    public function getCanceledAt(): ?\DateTime
    {
        if (count($this->canceledAt) == 0) {
            return null;
        }
        return $this->canceledAt['value'];
    }

    /**
     * Sets Canceled At.
     *
     * @maps canceled_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCanceledAt(?\DateTime $canceledAt): void
    {
        $this->canceledAt['value'] = $canceledAt;
    }

    /**
     * Unsets Canceled At.
     */
    public function unsetCanceledAt(): void
    {
        $this->canceledAt = [];
    }

    /**
     * Returns Discounts.
     * Subscription discounts
     *
     * @return GetDiscountResponse[]|null
     */
    public function getDiscounts(): ?array
    {
        if (count($this->discounts) == 0) {
            return null;
        }
        return $this->discounts['value'];
    }

    /**
     * Sets Discounts.
     * Subscription discounts
     *
     * @maps discounts
     *
     * @param GetDiscountResponse[]|null $discounts
     */
    public function setDiscounts(?array $discounts): void
    {
        $this->discounts['value'] = $discounts;
    }

    /**
     * Unsets Discounts.
     * Subscription discounts
     */
    public function unsetDiscounts(): void
    {
        $this->discounts = [];
    }

    /**
     * Returns Increments.
     * Subscription increments
     *
     * @return GetIncrementResponse[]|null
     */
    public function getIncrements(): ?array
    {
        if (count($this->increments) == 0) {
            return null;
        }
        return $this->increments['value'];
    }

    /**
     * Sets Increments.
     * Subscription increments
     *
     * @maps increments
     *
     * @param GetIncrementResponse[]|null $increments
     */
    public function setIncrements(?array $increments): void
    {
        $this->increments['value'] = $increments;
    }

    /**
     * Unsets Increments.
     * Subscription increments
     */
    public function unsetIncrements(): void
    {
        $this->increments = [];
    }

    /**
     * Returns Boleto Due Days.
     * Days until boleto expires
     */
    public function getBoletoDueDays(): ?int
    {
        if (count($this->boletoDueDays) == 0) {
            return null;
        }
        return $this->boletoDueDays['value'];
    }

    /**
     * Sets Boleto Due Days.
     * Days until boleto expires
     *
     * @maps boleto_due_days
     */
    public function setBoletoDueDays(?int $boletoDueDays): void
    {
        $this->boletoDueDays['value'] = $boletoDueDays;
    }

    /**
     * Unsets Boleto Due Days.
     * Days until boleto expires
     */
    public function unsetBoletoDueDays(): void
    {
        $this->boletoDueDays = [];
    }

    /**
     * Returns Split.
     * Subscription's split response
     */
    public function getSplit(): ?GetSubscriptionSplitResponse
    {
        if (count($this->split) == 0) {
            return null;
        }
        return $this->split['value'];
    }

    /**
     * Sets Split.
     * Subscription's split response
     *
     * @maps split
     */
    public function setSplit(?GetSubscriptionSplitResponse $split): void
    {
        $this->split['value'] = $split;
    }

    /**
     * Unsets Split.
     * Subscription's split response
     */
    public function unsetSplit(): void
    {
        $this->split = [];
    }

    /**
     * Returns Boleto.
     */
    public function getBoleto(): ?GetSubscriptionBoletoResponse
    {
        if (count($this->boleto) == 0) {
            return null;
        }
        return $this->boleto['value'];
    }

    /**
     * Sets Boleto.
     *
     * @maps boleto
     */
    public function setBoleto(?GetSubscriptionBoletoResponse $boleto): void
    {
        $this->boleto['value'] = $boleto;
    }

    /**
     * Unsets Boleto.
     */
    public function unsetBoleto(): void
    {
        $this->boleto = [];
    }

    /**
     * Returns Manual Billing.
     */
    public function getManualBilling(): ?bool
    {
        if (count($this->manualBilling) == 0) {
            return null;
        }
        return $this->manualBilling['value'];
    }

    /**
     * Sets Manual Billing.
     *
     * @maps manual_billing
     */
    public function setManualBilling(?bool $manualBilling): void
    {
        $this->manualBilling['value'] = $manualBilling;
    }

    /**
     * Unsets Manual Billing.
     */
    public function unsetManualBilling(): void
    {
        $this->manualBilling = [];
    }

    /**
     * Returns Indirect Acceptor.
     * Business model identifier
     */
    public function getIndirectAcceptor(): ?string
    {
        if (count($this->indirectAcceptor) == 0) {
            return null;
        }
        return $this->indirectAcceptor['value'];
    }

    /**
     * Sets Indirect Acceptor.
     * Business model identifier
     *
     * @maps indirect_acceptor
     */
    public function setIndirectAcceptor(?string $indirectAcceptor): void
    {
        $this->indirectAcceptor['value'] = $indirectAcceptor;
    }

    /**
     * Unsets Indirect Acceptor.
     * Business model identifier
     */
    public function unsetIndirectAcceptor(): void
    {
        $this->indirectAcceptor = [];
    }

    /**
     * Converts the GetSubscriptionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetSubscriptionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetSubscriptionResponse',
            [
                'id' => $this->getId(),
                'code' => $this->getCode(),
                'startAt' => $this->getStartAt(),
                'interval' => $this->getInterval(),
                'intervalCount' => $this->getIntervalCount(),
                'billingType' => $this->getBillingType(),
                'currentCycle' => $this->getCurrentCycle(),
                'paymentMethod' => $this->getPaymentMethod(),
                'currency' => $this->getCurrency(),
                'installments' => $this->getInstallments(),
                'status' => $this->getStatus(),
                'createdAt' => $this->getCreatedAt(),
                'updatedAt' => $this->getUpdatedAt(),
                'customer' => $this->getCustomer(),
                'card' => $this->getCard(),
                'items' => $this->getItems(),
                'statementDescriptor' => $this->getStatementDescriptor(),
                'metadata' => $this->getMetadata(),
                'setup' => $this->getSetup(),
                'gatewayAffiliationId' => $this->getGatewayAffiliationId(),
                'nextBillingAt' => $this->getNextBillingAt(),
                'billingDay' => $this->getBillingDay(),
                'minimumPrice' => $this->getMinimumPrice(),
                'canceledAt' => $this->getCanceledAt(),
                'discounts' => $this->getDiscounts(),
                'increments' => $this->getIncrements(),
                'boletoDueDays' => $this->getBoletoDueDays(),
                'split' => $this->getSplit(),
                'boleto' => $this->getBoleto(),
                'manualBilling' => $this->getManualBilling(),
                'indirectAcceptor' => $this->getIndirectAcceptor()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->id)) {
            $json['id']                     = $this->id['value'];
        }
        if (!empty($this->code)) {
            $json['code']                   = $this->code['value'];
        }
        if (!empty($this->startAt)) {
            $json['start_at']               = DateTimeHelper::toRfc3339DateTime($this->startAt['value']);
        }
        if (!empty($this->interval)) {
            $json['interval']               = $this->interval['value'];
        }
        if (!empty($this->intervalCount)) {
            $json['interval_count']         = $this->intervalCount['value'];
        }
        if (!empty($this->billingType)) {
            $json['billing_type']           = $this->billingType['value'];
        }
        if (!empty($this->currentCycle)) {
            $json['current_cycle']          = $this->currentCycle['value'];
        }
        if (!empty($this->paymentMethod)) {
            $json['payment_method']         = $this->paymentMethod['value'];
        }
        if (!empty($this->currency)) {
            $json['currency']               = $this->currency['value'];
        }
        if (!empty($this->installments)) {
            $json['installments']           = $this->installments['value'];
        }
        if (!empty($this->status)) {
            $json['status']                 = $this->status['value'];
        }
        if (!empty($this->createdAt)) {
            $json['created_at']             = DateTimeHelper::toRfc3339DateTime($this->createdAt['value']);
        }
        if (!empty($this->updatedAt)) {
            $json['updated_at']             = DateTimeHelper::toRfc3339DateTime($this->updatedAt['value']);
        }
        if (!empty($this->customer)) {
            $json['customer']               = $this->customer['value'];
        }
        if (!empty($this->card)) {
            $json['card']                   = $this->card['value'];
        }
        if (!empty($this->items)) {
            $json['items']                  = $this->items['value'];
        }
        if (!empty($this->statementDescriptor)) {
            $json['statement_descriptor']   = $this->statementDescriptor['value'];
        }
        if (!empty($this->metadata)) {
            $json['metadata']               = $this->metadata['value'];
        }
        if (!empty($this->setup)) {
            $json['setup']                  = $this->setup['value'];
        }
        if (!empty($this->gatewayAffiliationId)) {
            $json['gateway_affiliation_id'] = $this->gatewayAffiliationId['value'];
        }
        if (!empty($this->nextBillingAt)) {
            $json['next_billing_at']        = DateTimeHelper::toRfc3339DateTime($this->nextBillingAt['value']);
        }
        if (!empty($this->billingDay)) {
            $json['billing_day']            = $this->billingDay['value'];
        }
        if (!empty($this->minimumPrice)) {
            $json['minimum_price']          = $this->minimumPrice['value'];
        }
        if (!empty($this->canceledAt)) {
            $json['canceled_at']            = DateTimeHelper::toRfc3339DateTime($this->canceledAt['value']);
        }
        if (!empty($this->discounts)) {
            $json['discounts']              = $this->discounts['value'];
        }
        if (!empty($this->increments)) {
            $json['increments']             = $this->increments['value'];
        }
        if (!empty($this->boletoDueDays)) {
            $json['boleto_due_days']        = $this->boletoDueDays['value'];
        }
        if (!empty($this->split)) {
            $json['split']                  = $this->split['value'];
        }
        if (!empty($this->boleto)) {
            $json['boleto']                 = $this->boleto['value'];
        }
        if (!empty($this->manualBilling)) {
            $json['manual_billing']         = $this->manualBilling['value'];
        }
        if (!empty($this->indirectAcceptor)) {
            $json['indirect_acceptor']      = $this->indirectAcceptor['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
