<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Generic response object for getting a transaction.
 *
 * @discriminator transaction_type
 * @discriminatorType transaction
 */
class GetTransactionResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $gatewayId = [];

    /**
     * @var array
     */
    private $amount = [];

    /**
     * @var array
     */
    private $status = [];

    /**
     * @var array
     */
    private $success = [];

    /**
     * @var array
     */
    private $createdAt = [];

    /**
     * @var array
     */
    private $updatedAt = [];

    /**
     * @var array
     */
    private $attemptCount = [];

    /**
     * @var array
     */
    private $maxAttempts = [];

    /**
     * @var array
     */
    private $splits = [];

    /**
     * @var array
     */
    private $nextAttempt = [];

    /**
     * @var string|null
     */
    private $transactionType;

    /**
     * @var array
     */
    private $id = [];

    /**
     * @var array
     */
    private $gatewayResponse = [];

    /**
     * @var array
     */
    private $antifraudResponse = [];

    /**
     * @var array
     */
    private $metadata = [];

    /**
     * @var array
     */
    private $split = [];

    /**
     * @var array
     */
    private $interest = [];

    /**
     * @var array
     */
    private $fine = [];

    /**
     * @var array
     */
    private $maxDaysToPayPastDue = [];

    /**
     * Returns Gateway Id.
     * Gateway transaction id
     */
    public function getGatewayId(): ?string
    {
        if (count($this->gatewayId) == 0) {
            return null;
        }
        return $this->gatewayId['value'];
    }

    /**
     * Sets Gateway Id.
     * Gateway transaction id
     *
     * @maps gateway_id
     */
    public function setGatewayId(?string $gatewayId): void
    {
        $this->gatewayId['value'] = $gatewayId;
    }

    /**
     * Unsets Gateway Id.
     * Gateway transaction id
     */
    public function unsetGatewayId(): void
    {
        $this->gatewayId = [];
    }

    /**
     * Returns Amount.
     * Amount in cents
     */
    public function getAmount(): ?int
    {
        if (count($this->amount) == 0) {
            return null;
        }
        return $this->amount['value'];
    }

    /**
     * Sets Amount.
     * Amount in cents
     *
     * @maps amount
     */
    public function setAmount(?int $amount): void
    {
        $this->amount['value'] = $amount;
    }

    /**
     * Unsets Amount.
     * Amount in cents
     */
    public function unsetAmount(): void
    {
        $this->amount = [];
    }

    /**
     * Returns Status.
     * Transaction status
     */
    public function getStatus(): ?string
    {
        if (count($this->status) == 0) {
            return null;
        }
        return $this->status['value'];
    }

    /**
     * Sets Status.
     * Transaction status
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status['value'] = $status;
    }

    /**
     * Unsets Status.
     * Transaction status
     */
    public function unsetStatus(): void
    {
        $this->status = [];
    }

    /**
     * Returns Success.
     * Indicates if the transaction ocurred successfuly
     */
    public function getSuccess(): ?bool
    {
        if (count($this->success) == 0) {
            return null;
        }
        return $this->success['value'];
    }

    /**
     * Sets Success.
     * Indicates if the transaction ocurred successfuly
     *
     * @maps success
     */
    public function setSuccess(?bool $success): void
    {
        $this->success['value'] = $success;
    }

    /**
     * Unsets Success.
     * Indicates if the transaction ocurred successfuly
     */
    public function unsetSuccess(): void
    {
        $this->success = [];
    }

    /**
     * Returns Created At.
     * Creation date
     */
    public function getCreatedAt(): ?\DateTime
    {
        if (count($this->createdAt) == 0) {
            return null;
        }
        return $this->createdAt['value'];
    }

    /**
     * Sets Created At.
     * Creation date
     *
     * @maps created_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt['value'] = $createdAt;
    }

    /**
     * Unsets Created At.
     * Creation date
     */
    public function unsetCreatedAt(): void
    {
        $this->createdAt = [];
    }

    /**
     * Returns Updated At.
     * Last update date
     */
    public function getUpdatedAt(): ?\DateTime
    {
        if (count($this->updatedAt) == 0) {
            return null;
        }
        return $this->updatedAt['value'];
    }

    /**
     * Sets Updated At.
     * Last update date
     *
     * @maps updated_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt['value'] = $updatedAt;
    }

    /**
     * Unsets Updated At.
     * Last update date
     */
    public function unsetUpdatedAt(): void
    {
        $this->updatedAt = [];
    }

    /**
     * Returns Attempt Count.
     * Number of attempts tried
     */
    public function getAttemptCount(): ?int
    {
        if (count($this->attemptCount) == 0) {
            return null;
        }
        return $this->attemptCount['value'];
    }

    /**
     * Sets Attempt Count.
     * Number of attempts tried
     *
     * @maps attempt_count
     */
    public function setAttemptCount(?int $attemptCount): void
    {
        $this->attemptCount['value'] = $attemptCount;
    }

    /**
     * Unsets Attempt Count.
     * Number of attempts tried
     */
    public function unsetAttemptCount(): void
    {
        $this->attemptCount = [];
    }

    /**
     * Returns Max Attempts.
     * Max attempts
     */
    public function getMaxAttempts(): ?int
    {
        if (count($this->maxAttempts) == 0) {
            return null;
        }
        return $this->maxAttempts['value'];
    }

    /**
     * Sets Max Attempts.
     * Max attempts
     *
     * @maps max_attempts
     */
    public function setMaxAttempts(?int $maxAttempts): void
    {
        $this->maxAttempts['value'] = $maxAttempts;
    }

    /**
     * Unsets Max Attempts.
     * Max attempts
     */
    public function unsetMaxAttempts(): void
    {
        $this->maxAttempts = [];
    }

    /**
     * Returns Splits.
     * Splits
     *
     * @return GetSplitResponse[]|null
     */
    public function getSplits(): ?array
    {
        if (count($this->splits) == 0) {
            return null;
        }
        return $this->splits['value'];
    }

    /**
     * Sets Splits.
     * Splits
     *
     * @maps splits
     *
     * @param GetSplitResponse[]|null $splits
     */
    public function setSplits(?array $splits): void
    {
        $this->splits['value'] = $splits;
    }

    /**
     * Unsets Splits.
     * Splits
     */
    public function unsetSplits(): void
    {
        $this->splits = [];
    }

    /**
     * Returns Next Attempt.
     * Date and time of the next attempt
     */
    public function getNextAttempt(): ?\DateTime
    {
        if (count($this->nextAttempt) == 0) {
            return null;
        }
        return $this->nextAttempt['value'];
    }

    /**
     * Sets Next Attempt.
     * Date and time of the next attempt
     *
     * @maps next_attempt
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setNextAttempt(?\DateTime $nextAttempt): void
    {
        $this->nextAttempt['value'] = $nextAttempt;
    }

    /**
     * Unsets Next Attempt.
     * Date and time of the next attempt
     */
    public function unsetNextAttempt(): void
    {
        $this->nextAttempt = [];
    }

    /**
     * Returns Transaction Type.
     */
    public function getTransactionType(): ?string
    {
        return $this->transactionType;
    }

    /**
     * Sets Transaction Type.
     *
     * @maps transaction_type
     */
    public function setTransactionType(?string $transactionType): void
    {
        $this->transactionType = $transactionType;
    }

    /**
     * Returns Id.
     * Código da transação
     */
    public function getId(): ?string
    {
        if (count($this->id) == 0) {
            return null;
        }
        return $this->id['value'];
    }

    /**
     * Sets Id.
     * Código da transação
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id['value'] = $id;
    }

    /**
     * Unsets Id.
     * Código da transação
     */
    public function unsetId(): void
    {
        $this->id = [];
    }

    /**
     * Returns Gateway Response.
     * The Gateway Response
     */
    public function getGatewayResponse(): ?GetGatewayResponseResponse
    {
        if (count($this->gatewayResponse) == 0) {
            return null;
        }
        return $this->gatewayResponse['value'];
    }

    /**
     * Sets Gateway Response.
     * The Gateway Response
     *
     * @maps gateway_response
     */
    public function setGatewayResponse(?GetGatewayResponseResponse $gatewayResponse): void
    {
        $this->gatewayResponse['value'] = $gatewayResponse;
    }

    /**
     * Unsets Gateway Response.
     * The Gateway Response
     */
    public function unsetGatewayResponse(): void
    {
        $this->gatewayResponse = [];
    }

    /**
     * Returns Antifraud Response.
     */
    public function getAntifraudResponse(): ?GetAntifraudResponse
    {
        if (count($this->antifraudResponse) == 0) {
            return null;
        }
        return $this->antifraudResponse['value'];
    }

    /**
     * Sets Antifraud Response.
     *
     * @maps antifraud_response
     */
    public function setAntifraudResponse(?GetAntifraudResponse $antifraudResponse): void
    {
        $this->antifraudResponse['value'] = $antifraudResponse;
    }

    /**
     * Unsets Antifraud Response.
     */
    public function unsetAntifraudResponse(): void
    {
        $this->antifraudResponse = [];
    }

    /**
     * Returns Metadata.
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        if (count($this->metadata) == 0) {
            return null;
        }
        return $this->metadata['value'];
    }

    /**
     * Sets Metadata.
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata['value'] = $metadata;
    }

    /**
     * Unsets Metadata.
     */
    public function unsetMetadata(): void
    {
        $this->metadata = [];
    }

    /**
     * Returns Split.
     *
     * @return GetSplitResponse[]|null
     */
    public function getSplit(): ?array
    {
        if (count($this->split) == 0) {
            return null;
        }
        return $this->split['value'];
    }

    /**
     * Sets Split.
     *
     * @maps split
     *
     * @param GetSplitResponse[]|null $split
     */
    public function setSplit(?array $split): void
    {
        $this->split['value'] = $split;
    }

    /**
     * Unsets Split.
     */
    public function unsetSplit(): void
    {
        $this->split = [];
    }

    /**
     * Returns Interest.
     */
    public function getInterest(): ?GetInterestResponse
    {
        if (count($this->interest) == 0) {
            return null;
        }
        return $this->interest['value'];
    }

    /**
     * Sets Interest.
     *
     * @maps interest
     */
    public function setInterest(?GetInterestResponse $interest): void
    {
        $this->interest['value'] = $interest;
    }

    /**
     * Unsets Interest.
     */
    public function unsetInterest(): void
    {
        $this->interest = [];
    }

    /**
     * Returns Fine.
     */
    public function getFine(): ?GetFineResponse
    {
        if (count($this->fine) == 0) {
            return null;
        }
        return $this->fine['value'];
    }

    /**
     * Sets Fine.
     *
     * @maps fine
     */
    public function setFine(?GetFineResponse $fine): void
    {
        $this->fine['value'] = $fine;
    }

    /**
     * Unsets Fine.
     */
    public function unsetFine(): void
    {
        $this->fine = [];
    }

    /**
     * Returns Max Days to Pay Past Due.
     */
    public function getMaxDaysToPayPastDue(): ?int
    {
        if (count($this->maxDaysToPayPastDue) == 0) {
            return null;
        }
        return $this->maxDaysToPayPastDue['value'];
    }

    /**
     * Sets Max Days to Pay Past Due.
     *
     * @maps max_days_to_pay_past_due
     */
    public function setMaxDaysToPayPastDue(?int $maxDaysToPayPastDue): void
    {
        $this->maxDaysToPayPastDue['value'] = $maxDaysToPayPastDue;
    }

    /**
     * Unsets Max Days to Pay Past Due.
     */
    public function unsetMaxDaysToPayPastDue(): void
    {
        $this->maxDaysToPayPastDue = [];
    }

    /**
     * Converts the GetTransactionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetTransactionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetTransactionResponse',
            [
                'gatewayId' => $this->getGatewayId(),
                'amount' => $this->getAmount(),
                'status' => $this->getStatus(),
                'success' => $this->getSuccess(),
                'createdAt' => $this->getCreatedAt(),
                'updatedAt' => $this->getUpdatedAt(),
                'attemptCount' => $this->getAttemptCount(),
                'maxAttempts' => $this->getMaxAttempts(),
                'splits' => $this->getSplits(),
                'nextAttempt' => $this->getNextAttempt(),
                'transactionType' => $this->transactionType,
                'id' => $this->getId(),
                'gatewayResponse' => $this->getGatewayResponse(),
                'antifraudResponse' => $this->getAntifraudResponse(),
                'metadata' => $this->getMetadata(),
                'split' => $this->getSplit(),
                'interest' => $this->getInterest(),
                'fine' => $this->getFine(),
                'maxDaysToPayPastDue' => $this->getMaxDaysToPayPastDue()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->gatewayId)) {
            $json['gateway_id']               = $this->gatewayId['value'];
        }
        if (!empty($this->amount)) {
            $json['amount']                   = $this->amount['value'];
        }
        if (!empty($this->status)) {
            $json['status']                   = $this->status['value'];
        }
        if (!empty($this->success)) {
            $json['success']                  = $this->success['value'];
        }
        if (!empty($this->createdAt)) {
            $json['created_at']               = DateTimeHelper::toRfc3339DateTime($this->createdAt['value']);
        }
        if (!empty($this->updatedAt)) {
            $json['updated_at']               = DateTimeHelper::toRfc3339DateTime($this->updatedAt['value']);
        }
        if (!empty($this->attemptCount)) {
            $json['attempt_count']            = $this->attemptCount['value'];
        }
        if (!empty($this->maxAttempts)) {
            $json['max_attempts']             = $this->maxAttempts['value'];
        }
        if (!empty($this->splits)) {
            $json['splits']                   = $this->splits['value'];
        }
        if (!empty($this->nextAttempt)) {
            $json['next_attempt']             = DateTimeHelper::toRfc3339DateTime($this->nextAttempt['value']);
        }
        $json['transaction_type']             = $this->transactionType ?? 'transaction';
        if (!empty($this->id)) {
            $json['id']                       = $this->id['value'];
        }
        if (!empty($this->gatewayResponse)) {
            $json['gateway_response']         = $this->gatewayResponse['value'];
        }
        if (!empty($this->antifraudResponse)) {
            $json['antifraud_response']       = $this->antifraudResponse['value'];
        }
        if (!empty($this->metadata)) {
            $json['metadata']                 = $this->metadata['value'];
        }
        if (!empty($this->split)) {
            $json['split']                    = $this->split['value'];
        }
        if (!empty($this->interest)) {
            $json['interest']                 = $this->interest['value'];
        }
        if (!empty($this->fine)) {
            $json['fine']                     = $this->fine['value'];
        }
        if (!empty($this->maxDaysToPayPastDue)) {
            $json['max_days_to_pay_past_due'] = $this->maxDaysToPayPastDue['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
