<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Response object for listing BalanceOperation objects
 */
class ListBalanceOperationResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $data = [];

    /**
     * @var array
     */
    private $paging = [];

    /**
     * Returns Data.
     * The BalanceOperation object
     *
     * @return GetBalanceOperationResponse[]|null
     */
    public function getData(): ?array
    {
        if (count($this->data) == 0) {
            return null;
        }
        return $this->data['value'];
    }

    /**
     * Sets Data.
     * The BalanceOperation object
     *
     * @maps data
     *
     * @param GetBalanceOperationResponse[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data['value'] = $data;
    }

    /**
     * Unsets Data.
     * The BalanceOperation object
     */
    public function unsetData(): void
    {
        $this->data = [];
    }

    /**
     * Returns Paging.
     */
    public function getPaging(): ?PagingResponse
    {
        if (count($this->paging) == 0) {
            return null;
        }
        return $this->paging['value'];
    }

    /**
     * Sets Paging.
     *
     * @maps paging
     */
    public function setPaging(?PagingResponse $paging): void
    {
        $this->paging['value'] = $paging;
    }

    /**
     * Unsets Paging.
     */
    public function unsetPaging(): void
    {
        $this->paging = [];
    }

    /**
     * Converts the ListBalanceOperationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ListBalanceOperationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListBalanceOperationResponse',
            ['data' => $this->getData(), 'paging' => $this->getPaging()]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->data)) {
            $json['data']   = $this->data['value'];
        }
        if (!empty($this->paging)) {
            $json['paging'] = $this->paging['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
