<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use PagarmeApiSDKLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Request for updating a charge due date
 */
class UpdateChargeDueDateRequest implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $dueAt;

    /**
     * Returns Due At.
     * The charge's new due date
     */
    public function getDueAt(): ?\DateTime
    {
        return $this->dueAt;
    }

    /**
     * Sets Due At.
     * The charge's new due date
     *
     * @maps due_at
     * @factory \PagarmeApiSDKLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDueAt(?\DateTime $dueAt): void
    {
        $this->dueAt = $dueAt;
    }

    /**
     * Converts the UpdateChargeDueDateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateChargeDueDateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('UpdateChargeDueDateRequest', ['dueAt' => $this->dueAt]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->dueAt)) {
            $json['due_at'] = DateTimeHelper::toRfc3339DateTime($this->dueAt);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
