<?php

declare(strict_types=1);

/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PagarmeApiSDKLib\Models;

use PagarmeApiSDKLib\ApiHelper;
use stdClass;

/**
 * Update Order item Request
 */
class UpdateOrderItemRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $description;

    /**
     * @var int
     */
    private $quantity;

    /**
     * @var string
     */
    private $category;

    /**
     * @param int $amount
     * @param string $description
     * @param int $quantity
     * @param string $category
     */
    public function __construct(int $amount, string $description, int $quantity, string $category)
    {
        $this->amount = $amount;
        $this->description = $description;
        $this->quantity = $quantity;
        $this->category = $category;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @required
     * @maps quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Category.
     */
    public function getCategory(): string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     *
     * @required
     * @maps category
     */
    public function setCategory(string $category): void
    {
        $this->category = $category;
    }

    /**
     * Converts the UpdateOrderItemRequest object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateOrderItemRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpdateOrderItemRequest',
            [
                'amount' => $this->amount,
                'description' => $this->description,
                'quantity' => $this->quantity,
                'category' => $this->category
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']      = $this->amount;
        $json['description'] = $this->description;
        $json['quantity']    = $this->quantity;
        $json['category']    = $this->category;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
